import WarningAmberRounded from '@mui/icons-material/WarningAmberRounded';
import { type DragEvent, memo, useMemo, useState } from 'react';
import { TimelineHeader } from './TimelineHeader'; import { StatusBadge } from './StatusBadge';
import type { MestreWorkload, ObraCronograma, ZoomCronograma } from '../domain/models';
import { addDays, calculatedEnd, daysInMonth, monthDays, monthlyHeader, weeklyAllocation, weeklyHeader, yearDays } from '../domain/temporal';
import { getDropPlanningStart } from '../domain/dropPlanning'; import { getMestreColor, normalizeMestreKey } from '../domain/mestres'; import { getObraTemporalSegments, getTemporalSegmentsInBucket } from '../domain/obraTemporal';
interface Props { view: 'obras' | 'mestres'; zoom: ZoomCronograma; obras: ObraCronograma[]; workloads: MestreWorkload[]; selectedId: string | null; draggingMaster: string | null; leftWidth: number; onSelect: (obra: ObraCronograma) => void; onDropMaster: (obra: ObraCronograma, nome: string, target: string) => void; onResizeStart: (event: React.PointerEvent<HTMLDivElement>) => void; onResetResize: () => void; }
const civilOffset = (start: string, date: string) => Math.round((Date.parse(`${date}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000);
const colorStyle = (key: string): React.CSSProperties => ({ '--co-master-color': getMestreColor(key).background } as React.CSSProperties);
function TemporalLayer({ obra, start, days }: { obra: ObraCronograma; start: string; days: number }) { const segments = useMemo(() => getTemporalSegmentsInBucket(getObraTemporalSegments(obra), start, days), [obra, start, days]); return <span className="co-temporal-layer" aria-hidden="true">{segments.map((segment) => <i key={`${segment.type}-${segment.inicio}`} className={`co-temporal-segment is-${segment.type}`} style={{ left: `${civilOffset(start, segment.inicio) / days * 100}%`, width: `${(civilOffset(segment.inicio, segment.fim) + 1) / days * 100}%` }} />)}</span>; }
function MasterStrips({ obra, bucketStart, bucketDays }: { obra: ObraCronograma; bucketStart: string; bucketDays: number }) { const end = addDays(bucketStart, bucketDays - 1); const masters = obra.mestresPlanejados.filter((mestre) => mestre.inicio <= end && calculatedEnd(mestre.inicio, mestre.tempoPlanejado) >= bucketStart); return <span className="co-master-strips" aria-hidden="true">{masters.map((mestre, index) => { const inicio = mestre.inicio > bucketStart ? mestre.inicio : bucketStart; const fim = calculatedEnd(mestre.inicio, mestre.tempoPlanejado) < end ? calculatedEnd(mestre.inicio, mestre.tempoPlanejado) : end; return <i key={mestre.localId} className="co-master-strip" style={{ ...colorStyle(mestre.mestreKey ?? normalizeMestreKey(mestre.nome)), left: `${civilOffset(bucketStart, inicio) / bucketDays * 100}%`, width: `${(civilOffset(inicio, fim) + 1) / bucketDays * 100}%`, '--co-master-index': index, '--co-master-count': masters.length } as React.CSSProperties} />; })}</span>; }
function ObraCells({ obra, zoom, draggingMaster, onDrop }: { obra: ObraCronograma; zoom: ZoomCronograma; draggingMaster: string | null; onDrop: (target: string) => void }) { const [over, setOver] = useState<string | null>(null); const events = (target: string) => ({ onDragOver: (event: DragEvent) => { if (draggingMaster && getDropPlanningStart({ obra, zoom, targetDateOrPeriod: target })) { event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; } }, onDragEnter: () => { if (draggingMaster && getDropPlanningStart({ obra, zoom, targetDateOrPeriod: target })) setOver(target); }, onDragLeave: () => setOver((current) => current === target ? null : current), onDrop: (event: DragEvent) => { event.preventDefault(); event.stopPropagation(); setOver(null); if (draggingMaster) onDrop(target); } }); const cell = (start: string, days: number, className: string, plannedDays = 0, allocation?: { days: number; offset: number }) => { const valid = Boolean(getDropPlanningStart({ obra, zoom, targetDateOrPeriod: start })); return <div key={start} className={`${className} ${valid ? 'is-planned' : 'is-invalid-drop'} ${over === start ? 'is-drop-target' : ''}`} {...(valid ? events(start) : {})}><TemporalLayer obra={obra} start={start} days={days} />{allocation?.days ? <span className="co-allocation co-work-allocation" style={{ left: `${allocation.offset / days * 100}%`, width: `${allocation.days / days * 100}%` }}>{allocation.days < days ? allocation.days : ''}</span> : plannedDays ? <span className="co-allocation co-work-allocation">{plannedDays}</span> : null}<MasterStrips obra={obra} bucketStart={start} bucketDays={days} /></div>; };
  if (zoom === 'day') return <div className="co-day-cells">{yearDays(2026).map((date) => cell(date, 1, 'co-day-cell'))}</div>;
  if (zoom === 'month') return <div className="co-month-cells">{monthlyHeader(2026).map((month) => cell(month.start, monthDays(month.start), 'co-month-cell', daysInMonth(obra.inicioPlanejado, obra.tempoPlanejado, month.start)))}</div>;
  return <div className="co-week-cells">{weeklyHeader(2026).map((week) => cell(week, 7, 'co-week-cell', 0, weeklyAllocation(obra.inicioPlanejado, obra.tempoPlanejado, week)))}</div>; }
function MasterCells({ workload, zoom }: { workload: MestreWorkload; zoom: ZoomCronograma }) { const cells = zoom === 'day' ? workload.daily.map((item) => ({ days: item.obras.length, conflict: item.conflict })) : zoom === 'week' ? workload.weekly : monthlyHeader(2026).map((month) => { const items = workload.daily.filter((item) => item.date.slice(0, 7) === month.start.slice(0, 7)); return { days: items.filter((item) => item.obras.length).length, conflict: items.some((item) => item.conflict) }; }); return <div className={zoom === 'day' ? 'co-day-cells' : zoom === 'month' ? 'co-month-cells' : 'co-week-cells'}>{cells.map((cell, index) => <div className={`${zoom === 'day' ? 'co-day-cell' : zoom === 'month' ? 'co-month-cell' : 'co-week-cell'} co-resource-cell ${cell.conflict ? 'is-conflict' : ''}`} key={index}>{cell.days > 0 && <span className="co-resource-block" style={colorStyle(normalizeMestreKey(workload.mestre))} />}{cell.conflict && <WarningAmberRounded className="co-conflict-icon" />}</div>)}</div>; }
export const GanttGrid = memo(function GanttGrid({ view, zoom, obras, workloads, selectedId, draggingMaster, leftWidth, onSelect, onDropMaster, onResizeStart, onResetResize }: Props) { const rows = view === 'obras' ? obras.length : workloads.length; const style = { '--row-count': rows, '--co-left-width': `${leftWidth}px` } as React.CSSProperties; const left = view === 'obras' ? <><span>Obra</span><span>Mestre inicial</span><span>Status</span><span>Emp.</span><span>Início</span><span>Dias</span></> : <><span>Mestre</span><span>Obras</span><span>Dias</span><span>Livres</span><span>Conflitos</span></>; return <section className={`co-gantt co-gantt--${view} ${draggingMaster ? 'is-dragging-master' : ''}`} aria-label="Cronograma anual"><div className="co-gantt-scroll"><div className={`co-gantt-grid co-gantt-grid--${zoom}`} style={style}><div className="co-left-header">{left}</div><div className="co-column-resizer" role="separator" aria-label="Redimensionar tabela e calendário" aria-orientation="vertical" onPointerDown={onResizeStart} onDoubleClick={onResetResize} /><TimelineHeader zoom={zoom} />{view === 'obras' ? obras.map((obra) => <button type="button" className={`co-grid-row ${selectedId === obra.id ? 'is-selected' : ''}`} key={obra.id} onClick={() => onSelect(obra)}><div className="co-left-row"><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}</span><span>{obra.mestreInicial ?? <em>Sem mestre</em>}</span><span><StatusBadge status={obra.status} /></span><span>{obra.empresa}</span><span>{obra.inicioPlanejado}</span><span>{obra.tempoPlanejado}</span></div><div className="co-row-divider" /><ObraCells obra={obra} zoom={zoom} draggingMaster={draggingMaster} onDrop={(target) => onDropMaster(obra, draggingMaster!, target)} /></button>) : workloads.map((workload) => <div className="co-grid-row co-grid-row--resource" key={workload.mestre}><div className="co-left-row"><span className="co-master-name"><i className="co-master-swatch" style={colorStyle(normalizeMestreKey(workload.mestre))} />{workload.mestre}</span><span>{workload.obras.length}</span><span>{workload.diasProgramados}</span><span>{workload.freeDays} dias</span><span className={workload.conflictDays ? 'co-invalid-value' : ''}>{workload.conflictDays}</span></div><div className="co-row-divider" /><MasterCells workload={workload} zoom={zoom} /></div>)}</div></div>{!rows && <div className="co-empty">Nenhum resultado para os filtros selecionados.</div>}</section>; });
