import { collection, getDocs } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { db, functions } from '../firebase';
import { normalizarMovimentoCombustivel } from './combustivel-normalizer';
import { normalizeVehiclePlate, reportTotals } from './vehicle-report-core';

export { normalizeVehiclePlate } from './vehicle-report-core';
const n = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : Number(String(v ?? '').replace(',', '.')) || 0;
const text = (v: unknown) => String(v ?? '').trim();
const date = (v: any) => v?.toDate ? v.toDate() : new Date(v);
const iso = (v: any) => { const d = date(v); return Number.isNaN(d.getTime()) ? '' : d.toISOString().slice(0, 10); };
const year = (row: any) => Number(String(row.ano ?? row.mes ?? row.data_emissao ?? '').match(/20\d{2}/)?.[0]);
const movement = (row: any) => text(row.tipo_movimento).toUpperCase();
const sum = (items: any[], key: string) => items.reduce((total, item) => total + n(item[key]), 0);
const by = (items: any[], key: string, values: string[]) => Object.values(items.reduce((acc: any, item: any) => { const k = text(item[key]) || '—'; const result = acc[k] ??= { [key]: k, linhas: 0 }; result.linhas++; values.forEach((value) => result[value] = (result[value] ?? 0) + n(item[value])); return acc; }, {}));
function summarize46(rows: any[]) { const monthly = by(rows.map((r) => ({ ...r, mes: text(r.mes) || String(r.ano) })), 'mes', ['qtd_lancamentos', 'receita', 'despesa', 'valor_resultado']); return { linhas: rows.length, qtd_lancamentos: sum(rows, 'qtd_lancamentos'), receita: sum(rows, 'receita'), despesa: sum(rows, 'despesa'), valor_resultado: sum(rows, 'valor_resultado'), anual: [2025, 2026].map((ano) => { const a = rows.filter((r) => year(r) === ano); return { ano, ...summarize46Basic(a) }; }), mensal: monthly, contas: by(rows, 'conta', ['qtd_lancamentos', 'receita', 'despesa', 'valor_resultado']) }; }
function summarize46Basic(rows: any[]) { return { linhas: rows.length, qtd_lancamentos: sum(rows, 'qtd_lancamentos'), receita: sum(rows, 'receita'), despesa: sum(rows, 'despesa'), valor_resultado: sum(rows, 'valor_resultado') }; }
function summarize47(rows: any[]) { const expanded = rows.map((r) => ({ ...r, receita: movement(r) === 'RECEITA' ? n(r.valor_rateio) : 0, despesa: movement(r) === 'DESPESA' ? n(r.valor_rateio) : 0 })); const plate = expanded.reduce((a, r) => { const value = normalizeVehiclePlate(text(r.placa_nota)); if (!value) a.vazias++; else if (value === normalizeVehiclePlate(r.__placa)) a.preenchidas++; else a.divergentes++; return a; }, { preenchidas: 0, vazias: 0, divergentes: 0 }); const transfer = expanded.filter((r) => text(r.transferencia).toUpperCase() === 'S'); const basic = (items: any[]) => ({ linhas: items.length, notas: new Set(items.map((r) => text(r.numero_nota || r.cod_nota)).filter(Boolean)).size, fornecedores: new Set(items.map((r) => text(r.cliente_fornecedor)).filter(Boolean)).size, receita: sum(items, 'receita'), despesa: sum(items, 'despesa'), valor_rateio: sum(items, 'valor_rateio'), valor_resultado: sum(items, 'valor_resultado') }); return { ...basic(expanded), anual: [2025, 2026].map((ano) => ({ ano, ...basic(expanded.filter((r) => year(r) === ano)) })), mensal: by(expanded.map((r) => ({ ...r, mes: text(r.mes) || String(r.ano) })), 'mes', ['receita', 'despesa', 'valor_rateio', 'valor_resultado']), contas: by(expanded, 'conta', ['receita', 'despesa', 'valor_rateio', 'valor_resultado']), fornecedoresLista: by(expanded, 'cliente_fornecedor', ['receita', 'despesa', 'valor_rateio']), placa_nota: plate, transferencias: basic(transfer), detalhes: expanded.map((r) => ({ data: text(r.data_emissao), nota: text(r.numero_nota), fornecedor: text(r.cliente_fornecedor), natureza: text(r.natureza), conta: text(r.conta), tipo: text(r.tipo_movimento), valor_rateio: n(r.valor_rateio), placa_nota: text(r.placa_nota) || '—' })) }; }

export async function buildVehicleReport({ placa, vehicleId, vehicleName, dataInicial, dataFinal }: { placa: string; vehicleId: string; vehicleName?: string; dataInicial: string; dataFinal: string }) {
  const [fuelSnap, maintenanceSnap, erp] = await Promise.all([getDocs(collection(db, '03-combustivel')), getDocs(collection(db, 'manutencoes')), httpsCallable<any, any>(functions, 'getVehicleErpCosts')({ placa, dataInicial, dataFinal })]);
  const combustivel = fuelSnap.docs.map((d) => ({ id: d.id, ...normalizarMovimentoCombustivel(d.data(), d.id) as any })).filter((r: any) => r.isFuelOutput !== false && (r.itemFrotaUid === vehicleId || text(r.identificadorSnapshot) === placa || (!r.itemFrotaUid && text(r.placa) === placa)) && iso(r.data) >= dataInicial && iso(r.data) <= dataFinal).map((r: any) => ({ data: iso(r.data), litros: n(r.quantidadeAbastecida ?? r.qa), valor: n(r.valorAbastecimento ?? r.valor), km: r.km ?? null, obra: text(r.obra), motorista: text(r.motorista ?? r.paraQuem), id: r.id }));
  const manutencoes = maintenanceSnap.docs.map((d) => ({ id: d.id, ...d.data() as any })).filter((r: any) => (text(r.identificador) === placa || text(r.veiculoId) === vehicleId) && iso(r.data) >= dataInicial && iso(r.data) <= dataFinal).map((r: any) => ({ data: iso(r.data), descricao: text(r.descricao || r.categoriaNomeSnapshot || r.categoria), fornecedor: text(r.fornecedorNomeSnapshot || r.fornecedor), valor: n(r.valor), id: r.id }));
  const q46 = summarize46(erp.data.query46); const q47 = summarize47(erp.data.query47.map((r: any) => ({ ...r, __placa: placa })));
  const firebase = { combustivel: { registros: combustivel.length, litros: sum(combustivel, 'litros'), valor: sum(combustivel, 'valor'), itens: combustivel }, manutencoes: { registros: manutencoes.length, valor: sum(manutencoes, 'valor'), itens: manutencoes }, total: sum(combustivel, 'valor') + sum(manutencoes, 'valor') };
  return { veiculo: { placa, nome: vehicleName || placa }, periodo: { dataInicial, dataFinal }, firebase, erp: { query46: q46, query47: q47 }, totais: reportTotals(firebase.total, q46.despesa, q47.despesa) };
}
