import test from 'node:test';
import assert from 'node:assert/strict';
import { ALOCACOES_STORAGE_KEY, alocacoesDasObras, hydrateAlocacoes, loadAlocacoes, mergeAlocacoes, saveAlocacoes } from '../src/features/cronograma-obras/data/alocacoesLocal';
import type { ObraCronograma } from '../src/features/cronograma-obras/domain/models';

class MemoryStorage { private values = new Map<string, string>(); getItem(key: string) { return this.values.get(key) ?? null; } setItem(key: string, value: string) { this.values.set(key, value); } }
const masters = [{ id: 'm-joao', nome: 'João' }, { id: 'm-pedro', nome: 'Pedro' }];
const obra = (id = 'lote-a'): ObraCronograma => ({ id, sourceRow: 0, codObra: id, siglaObra: 'LOTE', nomeObra: id, local: id, status: 'Em execução', empresa: 'LEDUR', mestreInicial: null, descricao: null, inicioPlanejado: '2026-09-01', tempoPlanejado: 1, mestresPlanejados: [] });
const allocation = { id: 'periodo-1', obraId: 'lote-a', mestreId: 'm-joao', inicio: '2026-09-28', tempoPlanejado: 7 };

test('alocação persiste e hidrata pelo ID do LOTE e do mestre', () => { const storage = new MemoryStorage() as unknown as Storage; saveAlocacoes([allocation], storage); const reloaded = loadAlocacoes(storage); assert.deepEqual(reloaded, [allocation]); const hydrated = hydrateAlocacoes([obra(), obra('lote-b')], masters, reloaded); assert.equal(hydrated[0].mestresPlanejados[0].nome, 'João'); assert.equal(hydrated[0].mestresPlanejados[0].mestreId, 'm-joao'); assert.equal(hydrated[1].mestresPlanejados.length, 0); });
test('extensão, alteração de início, múltiplos mestres e períodos persistem sem duplicar', () => { const storage = new MemoryStorage() as unknown as Storage; const periods = [{ ...allocation, inicio: '2026-10-01', tempoPlanejado: 11 }, { id: 'periodo-2', obraId: 'lote-a', mestreId: 'm-joao', inicio: '2026-10-21', tempoPlanejado: 7 }, { id: 'periodo-3', obraId: 'lote-a', mestreId: 'm-pedro', inicio: '2026-10-01', tempoPlanejado: 7 }]; saveAlocacoes(periods, storage); const hydrated = hydrateAlocacoes([obra()], masters, loadAlocacoes(storage)); assert.equal(hydrated[0].mestresPlanejados.length, 3); assert.deepEqual(alocacoesDasObras(hydrated), periods); assert.equal(hydrateAlocacoes(hydrated, masters, periods)[0].mestresPlanejados.length, 3); });
test('merge preserva órfãos e remoções de períodos conhecidos', () => { const orphan = { id: 'orphan', obraId: 'lote-removido', mestreId: 'm-ausente', inicio: '2026-01-01', tempoPlanejado: 1 }; const current = [{ ...obra(), mestresPlanejados: [{ localId: 'periodo-4', mestreId: 'm-pedro', nome: 'Pedro', inicio: '2026-11-01', tempoPlanejado: 2 }] }]; assert.deepEqual(mergeAlocacoes([allocation, orphan], current, masters), [orphan, { id: 'periodo-4', obraId: 'lote-a', mestreId: 'm-pedro', inicio: '2026-11-01', tempoPlanejado: 2 }]); });
test('JSON inválido não derruba nem sobrescreve o armazenamento', () => { const storage = new MemoryStorage() as unknown as Storage; storage.setItem(ALOCACOES_STORAGE_KEY, '{inválido'); assert.deepEqual(loadAlocacoes(storage), []); assert.equal(storage.getItem(ALOCACOES_STORAGE_KEY), '{inválido'); });
