import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { adaptRawCronograma, requiresContractReview } from '../src/features/cronograma-obras/data/source/rawCronogramaAdapter';
import { adaptMestresFirestore, MESTRES_ESPERADOS } from '../src/features/cronograma-obras/data/mestresFirestoreAdapter';
import { inclusiveCivilDays } from '../src/features/cronograma-obras/domain/temporal';

const rawDoc = (id: string, obraV2Id: unknown, subitems: unknown = [], inicio: unknown = '2026-08-28') => ({ id, exists: true, data: { obraV2Id, raw: { id, nome: `Contrato ${id}`, empresa: 'LEDUR', status: 'Em execução', inicio, subitems } } });

test('monday-obras carrega dinamicamente somente documentos com obraV2Id preenchido', () => { const result = adaptRawCronograma([rawDoc('z', 'v2', []), rawDoc('a', 'v2', [{ id: 'lote-9', nome: 'LOTE 9' }]), rawDoc('null', null), rawDoc('empty', ''), rawDoc('space', '   '), rawDoc('missing', undefined)]); assert.deepEqual(result.contratos.map((item) => item.id), ['a', 'z']); assert.equal(result.contratos[0].obras[0].id, 'lote-9'); assert.deepEqual(result.contratos[1].obras.map((obra) => ({ id: obra.id, targetType: obra.targetType, nome: obra.nomeObra })), [{ id: 'contrato:z', targetType: 'contrato', nome: 'Analisar Contrato' }]); });
test('contrato sem LOTEs e sem raw.inicio mantém linha sintética, mas bloqueia criação temporal', () => { const result = adaptRawCronograma([rawDoc('a', 'v2', [], null)]); assert.equal(result.obras[0].allocationAllowed, false); assert.equal(result.obras[0].targetType, 'contrato'); });
test('datasource de obras é read-only e aponta para monday-obras', () => { const code = readFileSync('src/features/cronograma-obras/data/source/rawFirestoreCronogramaDataSource.ts', 'utf8'); assert.match(code, /monday-obras/); assert.doesNotMatch(code, /\b(setDoc|addDoc|updateDoc|deleteDoc|writeBatch|runTransaction)\b/); });
test('monday-mestres adapta catálogo e cores sem duplicações', () => { const result = adaptMestresFirestore(MESTRES_ESPERADOS.map(([id, nome, cor]) => ({ id, data: { nome, cor } }))); assert.deepEqual(result.mestres.map((item) => item.id), MESTRES_ESPERADOS.map(([id]) => id)); assert.equal(new Set(result.mestres.map((item) => item.cor.background)).size, 9); });
test('página usa monday-cronograma em tempo real, sem allowlist ou demo local', () => { const page = readFileSync('src/features/cronograma-obras/CronogramaObrasPage.tsx', 'utf8'); const repository = readFileSync('src/features/cronograma-obras/data/cronogramaFirestore.ts', 'utf8'); assert.match(page, /subscribeAlocacoes/); assert.doesNotMatch(page, /alocacoesLocal|CONTRATOS_HABILITADOS/); assert.match(repository, /monday-cronograma/); assert.match(repository, /onSnapshot/); assert.doesNotMatch(repository, /where\('contratoId', 'in'/); assert.match(repository, /updateDoc/); });
test('resize mantém draft local durante pointermove e persiste uma vez no pointerup', () => { const gantt = readFileSync('src/features/cronograma-obras/components/GanttGrid.tsx', 'utf8'); const page = readFileSync('src/features/cronograma-obras/CronogramaObrasPage.tsx', 'utf8'); assert.match(gantt, /onResizeMasterPreview\(draft\)/); assert.match(gantt, /onResizeMasterCommit\(obra\.id, draft\)/); assert.match(gantt, /onResizeMasterCancel\(mestre\.localId\)/); assert.match(page, /resizeDrafts\.current\.set/); assert.match(page, /await alocacoesSource\.updateAlocacao/); });
test('contrato preserva status real, fim e documento bruto de monday-obras', () => { const source = { id: 'c1', exists: true, data: { obraV2Id: 'obra-v2', sincronizacao: { origem: 'monday' }, raw: { nome: 'Contrato', status: 'Verificar Escopo da Obra', inicio: '2026-09-01', fim: '2026-09-07', subitems: [] } } }; const result = adaptRawCronograma([source]); const contrato = result.contratos[0]; assert.equal(contrato.status, 'Verificar Escopo da Obra'); assert.equal(contrato.fim, '2026-09-07'); assert.deepEqual(contrato.rawDocument, source.data); assert.equal(contrato.obras[0].nomeObra, 'Analisar Contrato'); });
test('status ausente usa fallback neutro e duração civil é inclusiva e segura', () => { const result = adaptRawCronograma([{ id: 'c1', exists: true, data: { obraV2Id: 'v2', raw: { nome: 'Contrato', inicio: '2026-09-01', fim: '2026-09-02', subitems: [{ id: 'l1', nome: 'Lote' }] } } }]); assert.equal(result.contratos[0].status, 'Sem status'); assert.equal(inclusiveCivilDays('2026-09-01', '2026-09-01'), 1); assert.equal(inclusiveCivilDays('2026-09-01', '2026-09-02'), 2); assert.equal(inclusiveCivilDays('2026-09-28', '2026-10-02'), 5); assert.equal(inclusiveCivilDays('2026-12-31', '2027-01-01'), 2); assert.equal(inclusiveCivilDays('2026-09-02', '2026-09-01'), null); assert.equal(inclusiveCivilDays('2026-02-30', '2026-03-01'), null); });
test('aviso contratual usa a mesma condição da linha sintética e desaparece com LOTEs', () => { const semLotes = adaptRawCronograma([rawDoc('sem', 'v2', [])]).contratos[0]; const comLotes = adaptRawCronograma([rawDoc('com', 'v2', [{ id: 'l1', nome: 'LOTE 1' }])]).contratos[0]; assert.equal(requiresContractReview(semLotes), true); assert.equal(semLotes.obras[0].nomeObra, 'Analisar Contrato'); assert.equal(requiresContractReview(comLotes), false); });
test('LOTE usa somente inicio/fim próprios para dias e período', () => { const lote = adaptRawCronograma([rawDoc('c1', 'v2', [{ id: 'l1', nome: 'LOTE 1', inicio: '2026-12-31', fim: '2027-01-02' }], '2026-09-01')]).obras[0]; const mesmoDia = adaptRawCronograma([rawDoc('c2', 'v2', [{ id: 'l2', nome: 'LOTE 2', inicio: '2026-09-01', fim: '2026-09-01' }])]).obras[0]; const semDatas = adaptRawCronograma([rawDoc('c3', 'v2', [{ id: 'l3', nome: 'LOTE 3' }], '2026-09-01')]).obras[0]; const invalido = adaptRawCronograma([rawDoc('c4', 'v2', [{ id: 'l4', nome: 'LOTE 4', inicio: '2026-10-02', fim: '2026-10-01' }])]).obras[0]; assert.deepEqual({ inicio: lote.inicioPlanejado, dias: lote.tempoPlanejado, periodo: lote.allocationAllowed }, { inicio: '2026-12-31', dias: 3, periodo: true }); assert.equal(mesmoDia.tempoPlanejado, 1); assert.equal(semDatas.allocationAllowed, false); assert.equal(invalido.allocationAllowed, false); });
test('grade destaca Analisar Contrato e separa detalhes do controle de expansão', () => { const gantt = readFileSync('src/features/cronograma-obras/components/GanttGrid.tsx', 'utf8'); const styles = readFileSync('src/features/cronograma-obras/styles/cronograma-obras.css', 'utf8'); const drawer = readFileSync('src/features/cronograma-obras/components/ContractDetailsDrawer.tsx', 'utf8'); assert.match(gantt, /MoreVertRounded/); assert.match(gantt, /event\.stopPropagation\(\).*onOpenContract/); assert.match(gantt, /StatusBadge status=\{contrato\?\.status/); assert.match(gantt, /inclusiveCivilDays\(contrato\?\.inicio, contrato\?\.fim\)/); assert.match(styles, /Analisar Contrato/); assert.match(drawer, /Ver bruto/); assert.match(drawer, /monday-obras/); assert.doesNotMatch(drawer, /setDoc|updateDoc|deleteDoc|addDoc/); });
