export const DESTINOS_OPTIONS: string[] = [
  "Fábrica",
  "Aceguá - RS",
  "Água Santa - RS",
  "Agudo - RS",
  "Ajuricaba - RS",
  "Alecrim - RS",
  "Alegrete - RS",
  "Alegria - RS",
  "Almirante Tamandaré do Sul - RS",
  "Alpestre - RS",
  "Alto Alegre - RS",
  "Alto Feliz - RS",
  "Alvorada - RS",
  "Amaral Ferrador - RS",
  "Ametista do Sul - RS",
  "André da Rocha - RS",
  "Anta Gorda - RS",
  "Antônio Prado - RS",
  "Arambaré - RS",
  "Araricá - RS",
  "Aratiba - RS",
  "Arroio do Meio - RS",
  "Arroio do Padre - RS",
  "Arroio do Sal - RS",
  "Arroio do Tigre - RS",
  "Arroio dos Ratos - RS",
  "Arroio Grande - RS",
  "Arvorezinha - RS",
  "Augusto Pestana - RS",
  "Áurea - RS",
  "Bagé - RS",
  "Balneário Pinhal - RS",
  "Barão - RS",
  "Barão de Cotegipe - RS",
  "Barão do Triunfo - RS",
  "Barra do Guarita - RS",
  "Barra do Quaraí - RS",
  "Barra do Ribeiro - RS",
  "Barra do Rio Azul - RS",
  "Barra Funda - RS",
  "Barracão - RS",
  "Barros Cassal - RS",
  "Benjamin Constant do Sul - RS",
  "Bento Gonçalves - RS",
  "Boa Vista das Missões - RS",
  "Boa Vista do Buricá - RS",
  "Boa Vista do Cadeado - RS",
  "Boa Vista do Incra - RS",
  "Boa Vista do Sul - RS",
  "Bom Jesus - RS",
  "Bom Princípio - RS",
  "Bom Progresso - RS",
  "Bom Retiro do Sul - RS",
  "Boqueirão do Leão - RS",
  "Bossoroca - RS",
  "Bozano - RS",
  "Braga - RS",
  "Brochier - RS",
  "Butiá - RS",
  "Caçapava do Sul - RS",
  "Cacequi - RS",
  "Cachoeira do Sul - RS",
  "Cachoeirinha - RS",
  "Cacique Doble - RS",
  "Caibaté - RS",
  "Caiçara - RS",
  "Camaquã - RS",
  "Camargo - RS",
  "Cambará do Sul - RS",
  "Campestre da Serra - RS",
  "Campina das Missões - RS",
  "Campinas do Sul - RS",
  "Campo Bom - RS",
  "Campo Novo - RS",
  "Campos Borges - RS",
  "Candelária - RS",
  "Cândido Godói - RS",
  "Candiota - RS",
  "Canela - RS",
  "Canguçu - RS",
  "Canoas - RS",
  "Canudos do Vale - RS",
  "Capão Bonito do Sul - RS",
  "Capão da Canoa - RS",
  "Capão do Cipó - RS",
  "Capão do Leão - RS",
  "Capela de Santana - RS",
  "Capitão - RS",
  "Capivari do Sul - RS",
  "Caraá - RS",
  "Carazinho - RS",
  "Carlos Barbosa - RS",
  "Carlos Gomes - RS",
  "Casca - RS",
  "Caseiros - RS",
  "Catuípe - RS",
  "Caxias do Sul - RS",
  "Centenário - RS",
  "Cerrito - RS",
  "Cerro Branco - RS",
  "Cerro Grande - RS",
  "Cerro Grande do Sul - RS",
  "Cerro Largo - RS",
  "Chapada - RS",
  "Charqueadas - RS",
  "Charrua - RS",
  "Chiapetta - RS",
  "Chuí - RS",
  "Chuvisca - RS",
  "Cidreira - RS",
  "Ciríaco - RS",
  "Colinas - RS",
  "Colorado - RS",
  "Condor - RS",
  "Constantina - RS",
  "Coqueiro Baixo - RS",
  "Coqueiros do Sul - RS",
  "Coronel Barros - RS",
  "Coronel Bicaco - RS",
  "Coronel Pilar - RS",
  "Cotiporã - RS",
  "Coxilha - RS",
  "Crissiumal - RS",
  "Cristal - RS",
  "Cristal do Sul - RS",
  "Cruz Alta - RS",
  "Cruzaltense - RS",
  "Cruzeiro do Sul - RS",
  "David Canabarro - RS",
  "Derrubadas - RS",
  "Dezesseis de Novembro - RS",
  "Dilermando de Aguiar - RS",
  "Dois Irmãos - RS",
  "Dois Irmãos das Missões - RS",
  "Dois Lajeados - RS",
  "Dom Feliciano - RS",
  "Dom Pedrito - RS",
  "Dom Pedro de Alcântara - RS",
  "Dona Francisca - RS",
  "Doutor Maurício Cardoso - RS",
  "Doutor Ricardo - RS",
  "Eldorado do Sul - RS",
  "Encantado - RS",
  "Encruzilhada do Sul - RS",
  "Engenho Velho - RS",
  "Entre-Ijuís - RS",
  "Entre Rios do Sul - RS",
  "Erebango - RS",
  "Erechim - RS",
  "Ernestina - RS",
  "Erval Grande - RS",
  "Erval Seco - RS",
  "Esmeralda - RS",
  "Esperança do Sul - RS",
  "Espumoso - RS",
  "Estação - RS",
  "Estância Velha - RS",
  "Esteio - RS",
  "Estrela - RS",
  "Estrela Velha - RS",
  "Eugênio de Castro - RS",
  "Fagundes Varela - RS",
  "Farroupilha - RS",
  "Faxinal do Soturno - RS",
  "Faxinalzinho - RS",
  "Fazenda Vilanova - RS",
  "Feliz - RS",
  "Flores da Cunha - RS",
  "Floriano Peixoto - RS",
  "Fontoura Xavier - RS",
  "Formigueiro - RS",
  "Forquetinha - RS",
  "Fortaleza dos Valos - RS",
  "Frederico Westphalen - RS",
  "Garibaldi - RS",
  "Garruchos - RS",
  "Gaurama - RS",
  "General Câmara - RS",
  "Gentil - RS",
  "Getúlio Vargas - RS",
  "Giruá - RS",
  "Glorinha - RS",
  "Gramado - RS",
  "Gramado dos Loureiros - RS",
  "Gramado Xavier - RS",
  "Gravataí - RS",
  "Guabiju - RS",
  "Guaíba - RS",
  "Guaporé - RS",
  "Guarani das Missões - RS",
  "Harmonia - RS",
  "Herval - RS",
  "Herveiras - RS",
  "Horizontina - RS",
  "Hulha Negra - RS",
  "Humaitá - RS",
  "Ibarama - RS",
  "Ibiaçá - RS",
  "Ibiraiaras - RS",
  "Ibirapuitã - RS",
  "Ibirubá - RS",
  "Igrejinha - RS",
  "Ijuí - RS",
  "Ilópolis - RS",
  "Imbé - RS",
  "Imigrante - RS",
  "Independência - RS",
  "Inhacorá - RS",
  "Ipê - RS",
  "Ipiranga do Sul - RS",
  "Iraí - RS",
  "Itaara - RS",
  "Itacurubi - RS",
  "Itapuca - RS",
  "Itaqui - RS",
  "Itati - RS",
  "Itatiba do Sul - RS",
  "Ivorá - RS",
  "Ivoti - RS",
  "Jaboticaba - RS",
  "Jacuizinho - RS",
  "Jacutinga - RS",
  "Jaguarão - RS",
  "Jaguari - RS",
  "Jaquirana - RS",
  "Jari - RS",
  "Jóia - RS",
  "Júlio de Castilhos - RS",
  "Lagoa Bonita do Sul - RS",
  "Lagoa dos Três Cantos - RS",
  "Lagoa Vermelha - RS",
  "Lagoão - RS",
  "Lajeado - RS",
  "Lajeado do Bugre - RS",
  "Lavras do Sul - RS",
  "Liberato Salzano - RS",
  "Lindolfo Collor - RS",
  "Linha Nova - RS",
  "Maçambará - RS",
  "Machadinho - RS",
  "Mampituba - RS",
  "Manoel Viana - RS",
  "Maquiné - RS",
  "Maratá - RS",
  "Marau - RS",
  "Marcelino Ramos - RS",
  "Mariana Pimentel - RS",
  "Mariano Moro - RS",
  "Marques de Souza - RS",
  "Mata - RS",
  "Mato Castelhano - RS",
  "Mato Leitão - RS",
  "Mato Queimado - RS",
  "Maximiliano de Almeida - RS",
  "Minas do Leão - RS",
  "Miraguaí - RS",
  "Montauri - RS",
  "Monte Alegre dos Campos - RS",
  "Monte Belo do Sul - RS",
  "Montenegro - RS",
  "Mormaço - RS",
  "Morrinhos do Sul - RS",
  "Morro Redondo - RS",
  "Morro Reuter - RS",
  "Mostardas - RS",
  "Muçum - RS",
  "Muitos Capões - RS",
  "Muliterno - RS",
  "Não-Me-Toque - RS",
  "Nicolau Vergueiro - RS",
  "Nonoai - RS",
  "Nova Alvorada - RS",
  "Nova Araçá - RS",
  "Nova Bassano - RS",
  "Nova Boa Vista - RS",
  "Nova Bréscia - RS",
  "Nova Candelária - RS",
  "Nova Esperança do Sul - RS",
  "Nova Hartz - RS",
  "Nova Pádua - RS",
  "Nova Palma - RS",
  "Nova Petrópolis - RS",
  "Nova Prata - RS",
  "Nova Ramada - RS",
  "Nova Roma do Sul - RS",
  "Nova Santa Rita - RS",
  "Novo Barreiro - RS",
  "Novo Cabrais - RS",
  "Novo Hamburgo - RS",
  "Novo Machado - RS",
  "Novo Tiradentes - RS",
  "Osório - RS",
  "Paim Filho - RS",
  "Palmares do Sul - RS",
  "Palmeira das Missões - RS",
  "Palmitinho - RS",
  "Panambi - RS",
  "Pantano Grande - RS",
  "Paraí - RS",
  "Paraíso do Sul - RS",
  "Pareci Novo - RS",
  "Parobé - RS",
  "Passa Sete - RS",
  "Passo do Sobrado - RS",
  "Passo Fundo - RS",
  "Paulo Bento - RS",
  "Paverama - RS",
  "Pedras Altas - RS",
  "Pedro Osório - RS",
  "Pejuçara - RS",
  "Pelotas - RS",
  "Picada Café - RS",
  "Pinhal - RS",
  "Pinhal da Serra - RS",
  "Pinhal Grande - RS",
  "Pinheirinho do Vale - RS",
  "Pinheiro Machado - RS",
  "Pinto Bandeira - RS",
  "Pirapó - RS",
  "Piratini - RS",
  "Planalto - RS",
  "Poço das Antas - RS",
  "Pontão - RS",
  "Ponte Preta - RS",
  "Portão - RS",
  "Porto Alegre - RS",
  "Porto Lucena - RS",
  "Porto Mauá - RS",
  "Porto Vera Cruz - RS",
  "Porto Xavier - RS",
  "Pouso Novo - RS",
  "Presidente Lucena - RS",
  "Progresso - RS",
  "Protásio Alves - RS",
  "Putinga - RS",
  "Quaraí - RS",
  "Quatro Irmãos - RS",
  "Quevedos - RS",
  "Quinze de Novembro - RS",
  "Redentora - RS",
  "Relvado - RS",
  "Restinga Seca - RS",
  "Rio dos Índios - RS",
  "Rio Grande - RS",
  "Rio Pardo - RS",
  "Riozinho - RS",
  "Roca Sales - RS",
  "Rodeio Bonito - RS",
  "Rolador - RS",
  "Rolante - RS",
  "Ronda Alta - RS",
  "Rondinha - RS",
  "Roque Gonzales - RS",
  "Rosário do Sul - RS",
  "Sagrada Família - RS",
  "Saúde - RS",
  "Salto do Jacuí - RS",
  "Salvador das Missões - RS",
  "Salvador do Sul - RS",
  "Sananduva - RS",
  "Santa Bárbara do Sul - RS",
  "Santa Cecília do Sul - RS",
  "Santa Clara do Sul - RS",
  "Santa Cruz do Sul - RS",
  "Santa Margarida do Sul - RS",
  "Santa Maria - RS",
  "Santa Maria do Herval - RS",
  "Santa Rosa - RS",
  "Santa Tereza - RS",
  "Santa Vitória do Palmar - RS",
  "Santana da Boa Vista - RS",
  "Santana do Livramento - RS",
  "Santiago - RS",
  "Santo Ângelo - RS",
  "Santo Antônio da Patrulha - RS",
  "Santo Antônio das Missões - RS",
  "Santo Antônio do Palma - RS",
  "Santo Antônio do Planalto - RS",
  "Santo Augusto - RS",
  "Santo Cristo - RS",
  "Santo Expedito do Sul - RS",
  "São Borja - RS",
  "São Domingos do Sul - RS",
  "São Francisco de Assis - RS",
  "São Francisco de Paula - RS",
  "São Gabriel - RS",
  "São Jerônimo - RS",
  "São João da Urtiga - RS",
  "São João do Polêsine - RS",
  "São Jorge - RS",
  "São José das Missões - RS",
  "São José do Herval - RS",
  "São José do Hortêncio - RS",
  "São José do Inhacorá - RS",
  "São José do Norte - RS",
  "São José do Ouro - RS",
  "São José dos Ausentes - RS",
  "São Leopoldo - RS",
  "São Lourenço do Sul - RS",
  "São Luiz Gonzaga - RS",
  "São Marcos - RS",
  "São Martinho - RS",
  "São Martinho da Serra - RS",
  "São Miguel das Missões - RS",
  "São Nicolau - RS",
  "São Paulo das Missões - RS",
  "São Pedro da Serra - RS",
  "São Pedro das Missões - RS",
  "São Pedro do Butiá - RS",
  "São Pedro do Sul - RS",
  "São Sebastião do Caí - RS",
  "São Sepé - RS",
  "São Valentim - RS",
  "São Valentim do Sul - RS",
  "São Valério do Sul - RS",
  "São Vendelino - RS",
  "São Vicente do Sul - RS",
  "Sapiranga - RS",
  "Sapucaia do Sul - RS",
  "Sarandi - RS",
  "Seberi - RS",
  "Sede Nova - RS",
  "Segredo - RS",
  "Selbach - RS",
  "Senador Salgado Filho - RS",
  "Sentinela do Sul - RS",
  "Serafina Corrêa - RS",
  "Sério - RS",
  "Sertão - RS",
  "Sertão Santana - RS",
  "Sete de Setembro - RS",
  "Severiano de Almeida - RS",
  "Silveira Martins - RS",
  "Sinimbu - RS",
  "Sobradinho - RS",
  "Soledade - RS",
  "Tabaí - RS",
  "Tapejara - RS",
  "Tapera - RS",
  "Tapes - RS",
  "Taquara - RS",
  "Taquari - RS",
  "Taquaruçu do Sul - RS",
  "Tavares - RS",
  "Tenente Portela - RS",
  "Terra de Areia - RS",
  "Teutônia - RS",
  "Tio Hugo - RS",
  "Tiradentes do Sul - RS",
  "Toropi - RS",
  "Torres - RS",
  "Tramandaí - RS",
  "Travesseiro - RS",
  "Três Arroios - RS",
  "Três Cachoeiras - RS",
  "Três Coroas - RS",
  "Três de Maio - RS",
  "Três Forquilhas - RS",
  "Três Palmeiras - RS",
  "Três Passos - RS",
  "Trindade do Sul - RS",
  "Triunfo - RS",
  "Tucunduva - RS",
  "Tunas - RS",
  "Tupanci do Sul - RS",
  "Tupanciretã - RS",
  "Tupandi - RS",
  "Tuparendi - RS",
  "Turuçu - RS",
  "Ubiretama - RS",
  "União da Serra - RS",
  "Unistalda - RS",
  "Uruguaiana - RS",
  "Vacaria - RS",
  "Vale do Sol - RS",
  "Vale Real - RS",
  "Vale Verde - RS",
  "Vanini - RS",
  "Venâncio Aires - RS",
  "Vera Cruz - RS",
  "Veranópolis - RS",
  "Vespasiano Corrêa - RS",
  "Viadutos - RS",
  "Viamão - RS",
  "Vicente Dutra - RS",
  "Victor Graeff - RS",
  "Vila Flores - RS",
  "Vila Lângaro - RS",
  "Vila Maria - RS",
  "Vila Nova do Sul - RS",
  "Vista Alegre - RS",
  "Vista Alegre do Prata - RS",
  "Vista Gaúcha - RS",
  "Vitória das Missões - RS",
  "Westfália - RS",
  "Xangri-lá - RS",
  "Abdon Batista - SC",
  "Abelardo Luz - SC",
  "Agrolândia - SC",
  "Agronômica - SC",
  "Água Doce - SC",
  "Águas de Chapecó - SC",
  "Águas Frias - SC",
  "Águas Mornas - SC",
  "Alfredo Wagner - SC",
  "Alto Bela Vista - SC",
  "Anchieta - SC",
  "Angelina - SC",
  "Anita Garibaldi - SC",
  "Anitápolis - SC",
  "Antônio Carlos - SC",
  "Apiúna - SC",
  "Arabutã - SC",
  "Araquari - SC",
  "Araranguá - SC",
  "Armazém - SC",
  "Arroio Trinta - SC",
  "Arvoredo - SC",
  "Ascurra - SC",
  "Atalanta - SC",
  "Aurora - SC",
  "Balneário Arroio do Silva - SC",
  "Balneário Barra do Sul - SC",
  "Balneário Camboriú - SC",
  "Balneário Gaivota - SC",
  "Balneário Piçarras - SC",
  "Balneário Rincão - SC",
  "Bandeirante - SC",
  "Barra Bonita - SC",
  "Barra Velha - SC",
  "Bela Vista do Toldo - SC",
  "Belmonte - SC",
  "Benedito Novo - SC",
  "Biguaçu - SC",
  "Blumenau - SC",
  "Bocaina do Sul - SC",
  "Bom Jardim da Serra - SC",
  "Bom Jesus - SC",
  "Bom Jesus do Oeste - SC",
  "Bom Retiro - SC",
  "Bombinhas - SC",
  "Botuverá - SC",
  "Braço do Norte - SC",
  "Braço do Trombudo - SC",
  "Brunópolis - SC",
  "Brusque - SC",
  "Caçador - SC",
  "Caibi - SC",
  "Calmon - SC",
  "Camboriú - SC",
  "Campo Alegre - SC",
  "Campo Belo do Sul - SC",
  "Campo Erê - SC",
  "Campos Novos - SC",
  "Canelinha - SC",
  "Canoinhas - SC",
  "Capão Alto - SC",
  "Capinzal - SC",
  "Capivari de Baixo - SC",
  "Catanduvas - SC",
  "Caxambu do Sul - SC",
  "Celso Ramos - SC",
  "Cerro Negro - SC",
  "Chapadão do Lageado - SC",
  "Chapecó - SC",
  "Cocal do Sul - SC",
  "Concórdia - SC",
  "Cordilheira Alta - SC",
  "Coronel Freitas - SC",
  "Coronel Martins - SC",
  "Correia Pinto - SC",
  "Corupá - SC",
  "Criciúma - SC",
  "Cunha Porã - SC",
  "Cunhataí - SC",
  "Curitibanos - SC",
  "Descanso - SC",
  "Dionísio Cerqueira - SC",
  "Dona Emma - SC",
  "Doutor Pedrinho - SC",
  "Entre Rios - SC",
  "Ermo - SC",
  "Erval Velho - SC",
  "Faxinal dos Guedes - SC",
  "Flor do Sertão - SC",
  "Florianópolis - SC",
  "Formosa do Sul - SC",
  "Forquilhinha - SC",
  "Fraiburgo - SC",
  "Frei Rogério - SC",
  "Galvão - SC",
  "Garopaba - SC",
  "Garuva - SC",
  "Gaspar - SC",
  "Governador Celso Ramos - SC",
  "Grão-Pará - SC",
  "Gravatal - SC",
  "Guabiruba - SC",
  "Guaraciaba - SC",
  "Guaramirim - SC",
  "Guarujá do Sul - SC",
  "Guatambu - SC",
  "Herval do Oeste - SC",
  "Ibiam - SC",
  "Ibicaré - SC",
  "Ibirama - SC",
  "Içara - SC",
  "Ilhota - SC",
  "Imaruí - SC",
  "Imbituba - SC",
  "Imbuia - SC",
  "Indaial - SC",
  "Iomerê - SC",
  "Ipira - SC",
  "Iporã do Oeste - SC",
  "Ipuaçu - SC",
  "Ipumirim - SC",
  "Iraceminha - SC",
  "Irani - SC",
  "Irati - SC",
  "Irineópolis - SC",
  "Itá - SC",
  "Itaiópolis - SC",
  "Itajaí - SC",
  "Itapema - SC",
  "Itapiranga - SC",
  "Itapoá - SC",
  "Ituporanga - SC",
  "Jaborá - SC",
  "Jacinto Machado - SC",
  "Jaguaruna - SC",
  "Jaraguá do Sul - SC",
  "Jardinópolis - SC",
  "Joaçaba - SC",
  "Joinville - SC",
  "José Boiteux - SC",
  "Jupiá - SC",
  "Lacerdópolis - SC",
  "Lages - SC",
  "Laguna - SC",
  "Lajeado Grande - SC",
  "Laurentino - SC",
  "Lauro Muller - SC",
  "Lebon Régis - SC",
  "Leoberto Leal - SC",
  "Lindóia do Sul - SC",
  "Lontras - SC",
  "Luiz Alves - SC",
  "Luzerna - SC",
  "Macieira - SC",
  "Mafra - SC",
  "Major Gercino - SC",
  "Major Vieira - SC",
  "Maracajá - SC",
  "Maravilha - SC",
  "Marema - SC",
  "Massaranduba - SC",
  "Matos Costa - SC",
  "Meleiro - SC",
  "Mirim Doce - SC",
  "Modelo - SC",
  "Mondaí - SC",
  "Monte Carlo - SC",
  "Monte Castelo - SC",
  "Morro da Fumaça - SC",
  "Morro Grande - SC",
  "Navegantes - SC",
  "Nova Erechim - SC",
  "Nova Itaberaba - SC",
  "Nova Trento - SC",
  "Nova Veneza - SC",
  "Novo Horizonte - SC",
  "Orleans - SC",
  "Otacílio Costa - SC",
  "Ouro - SC",
  "Ouro Verde - SC",
  "Paial - SC",
  "Painel - SC",
  "Palhoça - SC",
  "Palma Sola - SC",
  "Palmeira - SC",
  "Palmitos - SC",
  "Papanduva - SC",
  "Paraíso - SC",
  "Passo de Torres - SC",
  "Passos Maia - SC",
  "Paulo Lopes - SC",
  "Pedras Grandes - SC",
  "Penha - SC",
  "Peritiba - SC",
  "Pescaria Brava - SC",
  "Petrolândia - SC",
  "Pinhalzinho - SC",
  "Pinheiro Preto - SC",
  "Piratuba - SC",
  "Planalto Alegre - SC",
  "Pomerode - SC",
  "Ponte Alta - SC",
  "Ponte Alta do Norte - SC",
  "Ponte Serrada - SC",
  "Porto Belo - SC",
  "Porto União - SC",
  "Pouso Redondo - SC",
  "Praia Grande - SC",
  "Presidente Castello Branco - SC",
  "Presidente Getúlio - SC",
  "Presidente Nereu - SC",
  "Princesa - SC",
  "Quilombo - SC",
  "Rancho Queimado - SC",
  "Rio das Antas - SC",
  "Rio do Campo - SC",
  "Rio do Oeste - SC",
  "Rio do Sul - SC",
  "Rio dos Cedros - SC",
  "Rio Fortuna - SC",
  "Rio Negrinho - SC",
  "Rio Rufino - SC",
  "Riqueza - SC",
  "Rodeio - SC",
  "Romelândia - SC",
  "Salete - SC",
  "Saltinho - SC",
  "Salto Veloso - SC",
  "Sangão - SC",
  "Santa Cecília - SC",
  "Santa Helena - SC",
  "Santa Rosa de Lima - SC",
  "Santa Rosa do Sul - SC",
  "Santa Terezinha - SC",
  "Santa Terezinha do Progresso - SC",
  "Santiago do Sul - SC",
  "Santo Amaro da Imperatriz - SC",
  "São Bento do Sul - SC",
  "São Bernardino - SC",
  "São Bonifácio - SC",
  "São Carlos - SC",
  "São Cristóvão do Sul - SC",
  "São Domingos - SC",
  "São Francisco do Sul - SC",
  "São João Batista - SC",
  "São João do Itaperiú - SC",
  "São João do Oeste - SC",
  "São João do Sul - SC",
  "São Joaquim - SC",
  "São José - SC",
  "São José do Cedro - SC",
  "São José do Cerrito - SC",
  "São Lourenço do Oeste - SC",
  "São Ludgero - SC",
  "São Martinho - SC",
  "São Miguel da Boa Vista - SC",
  "São Miguel do Oeste - SC",
  "São Pedro de Alcântara - SC",
  "Saudades - SC",
  "Schroeder - SC",
  "Seara - SC",
  "Serra Alta - SC",
  "Siderópolis - SC",
  "Sombrio - SC",
  "Sul Brasil - SC",
  "Taió - SC",
  "Tangará - SC",
  "Tigrinhos - SC",
  "Tijucas - SC",
  "Timbé do Sul - SC",
  "Timbó - SC",
  "Timbó Grande - SC",
  "Três Barras - SC",
  "Treviso - SC",
  "Treze de Maio - SC",
  "Treze Tílias - SC",
  "Trombudo Central - SC",
  "Tubarão - SC",
  "Tunápolis - SC",
  "Turvo - SC",
  "União do Oeste - SC",
  "Urubici - SC",
  "Urupema - SC",
  "Urussanga - SC",
  "Vargeão - SC",
  "Vargem - SC",
  "Vargem Bonita - SC",
  "Vidal Ramos - SC",
  "Videira - SC",
  "Vitor Meireles - SC",
  "Witmarsum - SC",
  "Xanxerê - SC",
  "Xavantina - SC",
  "Xaxim - SC",
  "Zortéa - SC",
  "Abatiá - PR",
  "Adrianópolis - PR",
  "Agudos do Sul - PR",
  "Almirante Tamandaré - PR",
  "Altamira do Paraná - PR",
  "Altônia - PR",
  "Alto Paraná - PR",
  "Alto Piquiri - PR",
  "Alvorada do Sul - PR",
  "Amaporã - PR",
  "Ampére - PR",
  "Anahy - PR",
  "Andirá - PR",
  "Ângulo - PR",
  "Antonina - PR",
  "Antônio Olinto - PR",
  "Apucarana - PR",
  "Arapongas - PR",
  "Arapoti - PR",
  "Arapuã - PR",
  "Araruna - PR",
  "Araucária - PR",
  "Ariranha do Ivaí - PR",
  "Assaí - PR",
  "Assis Chateaubriand - PR",
  "Astorga - PR",
  "Atalaia - PR",
  "Balsa Nova - PR",
  "Bandeirantes - PR",
  "Barbosa Ferraz - PR",
  "Barra do Jacaré - PR",
  "Barracão - PR",
  "Bela Vista da Caroba - PR",
  "Bela Vista do Paraíso - PR",
  "Bituruna - PR",
  "Boa Esperança - PR",
  "Boa Esperança do Iguaçu - PR",
  "Boa Ventura de São Roque - PR",
  "Boa Vista da Aparecida - PR",
  "Bocaiúva do Sul - PR",
  "Bom Jesus do Sul - PR",
  "Bom Sucesso - PR",
  "Bom Sucesso do Sul - PR",
  "Borrazópolis - PR",
  "Braganey - PR",
  "Brasilândia do Sul - PR",
  "Cafeara - PR",
  "Cafelândia - PR",
  "Cafezal do Sul - PR",
  "Califórnia - PR",
  "Cambará - PR",
  "Cambé - PR",
  "Cambira - PR",
  "Campina da Lagoa - PR",
  "Campina do Simão - PR",
  "Campina Grande do Sul - PR",
  "Campo Bonito - PR",
  "Campo do Tenente - PR",
  "Campo Largo - PR",
  "Campo Magro - PR",
  "Campo Mourão - PR",
  "Cândido de Abreu - PR",
  "Candói - PR",
  "Cantagalo - PR",
  "Capanema - PR",
  "Capitão Leônidas Marques - PR",
  "Carambeí - PR",
  "Carlópolis - PR",
  "Cascavel - PR",
  "Castro - PR",
  "Catanduvas - PR",
  "Centenário do Sul - PR",
  "Cerro Azul - PR",
  "Céu Azul - PR",
  "Chopinzinho - PR",
  "Cianorte - PR",
  "Cidade Gaúcha - PR",
  "Clevelândia - PR",
  "Colombo - PR",
  "Colorado - PR",
  "Congonhinhas - PR",
  "Conselheiro Mairinck - PR",
  "Contenda - PR",
  "Corbélia - PR",
  "Cornélio Procópio - PR",
  "Coronel Domingos Soares - PR",
  "Coronel Vivida - PR",
  "Corumbataí do Sul - PR",
  "Cruz Machado - PR",
  "Cruzeiro do Iguaçu - PR",
  "Cruzeiro do Oeste - PR",
  "Cruzeiro do Sul - PR",
  "Cruzmaltina - PR",
  "Curitiba - PR",
  "Curiúva - PR",
  "Diamante do Oeste - PR",
  "Diamante do Norte - PR",
  "Diamante do Sul - PR",
  "Dois Vizinhos - PR",
  "Douradina - PR",
  "Doutor Camargo - PR",
  "Doutor Ulysses - PR",
  "Enéas Marques - PR",
  "Engenheiro Beltrão - PR",
  "Entre Rios do Oeste - PR",
  "Esperança Nova - PR",
  "Espigão Alto do Iguaçu - PR",
  "Farol - PR",
  "Faxinal - PR",
  "Fazenda Rio Grande - PR",
  "Fênix - PR",
  "Fernandes Pinheiro - PR",
  "Figueira - PR",
  "Flor da Serra do Sul - PR",
  "Floraí - PR",
  "Floresta - PR",
  "Florestópolis - PR",
  "Flórida - PR",
  "Formosa do Oeste - PR",
  "Foz do Iguaçu - PR",
  "Foz do Jordão - PR",
  "Francisco Alves - PR",
  "Francisco Beltrão - PR",
  "General Carneiro - PR",
  "Godoy Moreira - PR",
  "Goioerê - PR",
  "Goioxim - PR",
  "Grandes Rios - PR",
  "Guaíra - PR",
  "Guairaçá - PR",
  "Guamiranga - PR",
  "Guapirama - PR",
  "Guaporema - PR",
  "Guaraci - PR",
  "Guaraniaçu - PR",
  "Guarapuava - PR",
  "Guaraqueçaba - PR",
  "Guaratuba - PR",
  "Honório Serpa - PR",
  "Icaraíma - PR",
  "Ibaiti - PR",
  "Ibema - PR",
  "Ibiporã - PR",
  "Icaraíma - PR",
  "Imbaú - PR",
  "Imbituva - PR",
  "Inácio Martins - PR",
  "Inajá - PR",
  "Indianópolis - PR",
  "Ipiranga - PR",
  "Iporã - PR",
  "Iracema do Oeste - PR",
  "Irati - PR",
  "Iretama - PR",
  "Itaguajé - PR",
  "Itaipulândia - PR",
  "Itambaracá - PR",
  "Itambé - PR",
  "Itapejara do Oeste - PR",
  "Itaperuçu - PR",
  "Itaúna do Sul - PR",
  "Ivaí - PR",
  "Ivaiporã - PR",
  "Ivaté - PR",
  "Ivatuba - PR",
  "Jaboti - PR",
  "Jacarezinho - PR",
  "Jaguapitã - PR",
  "Jaguariaíva - PR",
  "Jandaia do Sul - PR",
  "Janiópolis - PR",
  "Japira - PR",
  "Japurá - PR",
  "Jardim Alegre - PR",
  "Jardim Olinda - PR",
  "Jataizinho - PR",
  "Jesuítas - PR",
  "Joaquim Távora - PR",
  "Jundiaí do Sul - PR",
  "Juranda - PR",
  "Jussara - PR",
  "Kaloré - PR",
  "Lapa - PR",
  "Laranjal - PR",
  "Laranjeiras do Sul - PR",
  "Leópolis - PR",
  "Lidianópolis - PR",
  "Lindoeste - PR",
  "Loanda - PR",
  "Lobato - PR",
  "Londrina - PR",
  "Luiziana - PR",
  "Lunardelli - PR",
  "Lupionópolis - PR",
  "Mallet - PR",
  "Mamborê - PR",
  "Mandaguaçu - PR",
  "Mandaguari - PR",
  "Mandirituba - PR",
  "Manfrinópolis - PR",
  "Mangueirinha - PR",
  "Manoel Ribas - PR",
  "Marechal Cândido Rondon - PR",
  "Maria Helena - PR",
  "Marialva - PR",
  "Marilândia do Sul - PR",
  "Marilena - PR",
  "Mariluz - PR",
  "Maringá - PR",
  "Mariópolis - PR",
  "Maripá - PR",
  "Marmeleiro - PR",
  "Marquinho - PR",
  "Marumbi - PR",
  "Matelândia - PR",
  "Matinhos - PR",
  "Mato Rico - PR",
  "Mauá da Serra - PR",
  "Medianeira - PR",
  "Mercedes - PR",
  "Mirador - PR",
  "Miraselva - PR",
  "Missal - PR",
  "Moreira Sales - PR",
  "Morretes - PR",
  "Munhoz de Melo - PR",
  "Nossa Senhora das Graças - PR",
  "Nova Aliança do Ivaí - PR",
  "Nova América da Colina - PR",
  "Nova Aurora - PR",
  "Nova Cantu - PR",
  "Nova Esperança - PR",
  "Nova Esperança do Sudoeste - PR",
  "Nova Fátima - PR",
  "Nova Laranjeiras - PR",
  "Nova Londrina - PR",
  "Nova Olímpia - PR",
  "Nova Prata do Iguaçu - PR",
  "Novo Itacolomi - PR",
  "Ortigueira - PR",
  "Ourizona - PR",
  "Ouro Verde do Oeste - PR",
  "Paiçandu - PR",
  "Palmas - PR",
  "Palmeira - PR",
  "Palmital - PR",
  "Palotina - PR",
  "Paraíso do Norte - PR",
  "Paranacity - PR",
  "Paranaguá - PR",
  "Paranapoema - PR",
  "Paranavaí - PR",
  "Pato Bragado - PR",
  "Pato Branco - PR",
  "Paula Freitas - PR",
  "Paulo Frontin - PR",
  "Peabiru - PR",
  "Perobal - PR",
  "Pérola - PR",
  "Pérola do Oeste - PR",
  "Piên - PR",
  "Pinhais - PR",
  "Pinhal de São Bento - PR",
  "Pinhalão - PR",
  "Pinhão - PR",
  "Piraí do Sul - PR",
  "Piraquara - PR",
  "Pitanga - PR",
  "Pitangueiras - PR",
  "Planaltina do Paraná - PR",
  "Planalto - PR",
  "Ponta Grossa - PR",
  "Pontal do Paraná - PR",
  "Porecatu - PR",
  "Porto Amazonas - PR",
  "Porto Barreiro - PR",
  "Porto Rico - PR",
  "Porto Vitória - PR",
  "Prado Ferreira - PR",
  "Pranchita - PR",
  "Presidente Castelo Branco - PR",
  "Primeiro de Maio - PR",
  "Prudentópolis - PR",
  "Quarto Centenário - PR",
  "Quatiguá - PR",
  "Quatro Barras - PR",
  "Quatro Pontes - PR",
  "Quedas do Iguaçu - PR",
  "Querência do Norte - PR",
  "Quinta do Sol - PR",
  "Quitandinha - PR",
  "Ramilândia - PR",
  "Rancho Alegre - PR",
  "Rancho Alegre do Oeste - PR",
  "Realeza - PR",
  "Rebouças - PR",
  "Renascença - PR",
  "Reserva - PR",
  "Reserva do Iguaçu - PR",
  "Ribeirão Claro - PR",
  "Ribeirão do Pinhal - PR",
  "Rio Azul - PR",
  "Rio Bom - PR",
  "Rio Bonito do Iguaçu - PR",
  "Rio Branco do Ivaí - PR",
  "Rio Branco do Sul - PR",
  "Rio Negro - PR",
  "Rolândia - PR",
  "Roncador - PR",
  "Rondon - PR",
  "Rosário do Ivaí - PR",
  "Sabáudia - PR",
  "Salgado Filho - PR",
  "Salto do Itararé - PR",
  "Salto do Lontra - PR",
  "Santa Amélia - PR",
  "Santa Cecília do Pavão - PR",
  "Santa Cruz de Monte Castelo - PR",
  "Santa Fé - PR",
  "Santa Helena - PR",
  "Santa Inês - PR",
  "Santa Isabel do Ivaí - PR",
  "Santa Izabel do Oeste - PR",
  "Santa Lúcia - PR",
  "Santa Maria do Oeste - PR",
  "Santa Mariana - PR",
  "Santa Mônica - PR",
  "Santa Tereza do Oeste - PR",
  "Santa Terezinha de Itaipu - PR",
  "Santana do Itararé - PR",
  "Santo Antônio da Platina - PR",
  "Santo Antônio do Caiuá - PR",
  "Santo Antônio do Paraíso - PR",
  "Santo Antônio do Sudoeste - PR",
  "Santo Inácio - PR",
  "São Carlos do Ivaí - PR",
  "São Jerônimo da Serra - PR",
  "São João - PR",
  "São João do Caiuá - PR",
  "São João do Ivaí - PR",
  "São João do Triunfo - PR",
  "São Jorge do Ivaí - PR",
  "São Jorge do Patrocínio - PR",
  "São José da Boa Vista - PR",
  "São José das Palmeiras - PR",
  "São José dos Pinhais - PR",
  "São Manoel do Paraná - PR",
  "São Mateus do Sul - PR",
  "São Miguel do Iguaçu - PR",
  "São Pedro do Iguaçu - PR",
  "São Pedro do Ivaí - PR",
  "São Pedro do Paraná - PR",
  "São Sebastião da Amoreira - PR",
  "São Tomé - PR",
  "Sapopema - PR",
  "Sarandi - PR",
  "Saudade do Iguaçu - PR",
  "Sengés - PR",
  "Serranópolis do Iguaçu - PR",
  "Sertaneja - PR",
  "Sertanópolis - PR",
  "Siqueira Campos - PR",
  "Sulina - PR",
  "Tamarana - PR",
  "Tamboara - PR",
  "Tapejara - PR",
  "Tapira - PR",
  "Teixeira Soares - PR",
  "Telêmaco Borba - PR",
  "Terra Boa - PR",
  "Terra Rica - PR",
  "Terra Roxa - PR",
  "Tibagi - PR",
  "Tijucas do Sul - PR",
  "Toledo - PR",
  "Tomazina - PR",
  "Três Barras do Paraná - PR",
  "Tunas do Paraná - PR",
  "Tuneiras do Oeste - PR",
  "Tupãssi - PR",
  "Turvo - PR",
  "Ubiratã - PR",
  "Umuarama - PR",
  "União da Vitória - PR",
  "Uniflor - PR",
  "Uraí - PR",
  "Ventania - PR",
  "Vera Cruz do Oeste - PR",
  "Verê - PR",
  "Virmond - PR",
  "Vitorino - PR",
  "Wenceslau Braz - PR",
  "Xambrê - PR",
];