import WarningAmberRounded from '@mui/icons-material/WarningAmberRounded';
import { type DragEvent, memo, useMemo, useState } from 'react';
import { TimelineHeader } from './TimelineHeader';
import { StatusBadge } from './StatusBadge';
import type { MestreWorkload, ObraCronograma, ZoomCronograma } from '../domain/models';
import { monthDays, monthlyHeader, weeklyHeader, yearDays } from '../domain/temporal';
import { getDropPlanningStart } from '../domain/dropPlanning';
import { getMestreColor, normalizeMestreKey } from '../domain/mestres';
import { getBucketTimelineAggregate, getWeeklyTimeline } from '../domain/timelineAggregation';

interface Props { view: 'obras' | 'mestres'; zoom: ZoomCronograma; obras: ObraCronograma[]; workloads: MestreWorkload[]; selectedId: string | null; draggingMaster: string | null; onSelect: (obra: ObraCronograma) => void; onDropMaster: (obra: ObraCronograma, nome: string, target: string) => void; }
const colorStyle = (key: string): React.CSSProperties => ({ '--co-master-color': getMestreColor(key).background } as React.CSSProperties);
function TemporalLayer({ obra, start, days }: { obra: ObraCronograma; start: string; days: number }) { const aggregate = useMemo(() => getBucketTimelineAggregate(obra, start, days), [obra, start, days]); return <span className="co-temporal-layer" aria-hidden="true">{aggregate.states.map((segment) => <i key={`${segment.type}-${segment.offset}`} className={`co-temporal-segment is-${segment.type}`} style={{ left: `${segment.offset / days * 100}%`, width: `${segment.days / days * 100}%` }} />)}</span>; }
function MasterStrips({ obra, bucketStart, bucketDays }: { obra: ObraCronograma; bucketStart: string; bucketDays: number }) { const aggregate = useMemo(() => getBucketTimelineAggregate(obra, bucketStart, bucketDays), [obra, bucketStart, bucketDays]); return <span className="co-master-strips" aria-hidden="true">{aggregate.masters.map((segment, index) => <i key={segment.mestre.localId} className="co-master-strip" style={{ ...colorStyle(segment.mestre.mestreKey ?? normalizeMestreKey(segment.mestre.nome)), left: `${segment.offset / bucketDays * 100}%`, width: `${segment.days / bucketDays * 100}%`, '--co-master-index': index, '--co-master-count': aggregate.masters.length } as React.CSSProperties} />)}</span>; }
function MonthSummary({ obra, start, days }: { obra: ObraCronograma; start: string; days: number }) { const aggregate = useMemo(() => getBucketTimelineAggregate(obra, start, days), [obra, start, days]); const masters = [...new Map(aggregate.masters.map((segment) => [segment.mestre.localId, segment.mestre])).values()]; return <div className="co-month-summary"><span className="co-month-state" aria-hidden="true">{aggregate.states.map((segment) => <i key={`${segment.type}-${segment.offset}`} className={`is-${segment.type}`} style={{ flex: segment.days }} />)}</span><strong>{aggregate.plannedDays || ''}</strong><span className="co-month-masters" aria-label={masters.length ? `${masters.length} mestre(s) planejado(s)` : undefined}>{masters.slice(0, 3).map((mestre) => <i key={mestre.localId} style={colorStyle(mestre.mestreKey ?? normalizeMestreKey(mestre.nome))} />)}{masters.length > 3 && <small>+{masters.length - 3}</small>}</span></div>; }
function WeeklyLanes({ obra, week }: { obra: ObraCronograma; week: string }) { const timeline = useMemo(() => getWeeklyTimeline(obra, week), [obra, week]); return <div className="co-week-lanes"><span className="co-week-temporal" aria-hidden="true">{timeline.states.map((segment) => <i key={`${segment.type}-${segment.startDayIndex}`} className={`is-${segment.type}`} style={{ left: `${segment.startDayIndex / 7 * 100}%`, width: `${segment.dayCount / 7 * 100}%` }} />)}</span><span className="co-week-space">{timeline.plannedDays > 0 && timeline.plannedDays < 7 ? <b>{timeline.plannedDays}</b> : null}</span><span className="co-week-masters" aria-hidden="true">{timeline.masters.map((segment, index) => <i key={segment.mestre.localId} style={{ ...colorStyle(segment.mestre.mestreKey ?? normalizeMestreKey(segment.mestre.nome)), left: `${segment.startDayIndex / 7 * 100}%`, width: `${segment.dayCount / 7 * 100}%`, '--co-week-master-index': index, '--co-week-master-count': timeline.masters.length } as React.CSSProperties} />)}</span></div>; }
function ObraCells({ obra, zoom, draggingMaster, onDrop }: { obra: ObraCronograma; zoom: ZoomCronograma; draggingMaster: string | null; onDrop: (target: string) => void }) { const [over, setOver] = useState<string | null>(null); const events = (target: string) => ({ onDragOver: (event: DragEvent) => { if (draggingMaster && getDropPlanningStart({ obra, zoom, targetDateOrPeriod: target })) { event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; } }, onDragEnter: () => { if (draggingMaster && getDropPlanningStart({ obra, zoom, targetDateOrPeriod: target })) setOver(target); }, onDragLeave: () => setOver((current) => current === target ? null : current), onDrop: (event: DragEvent) => { event.preventDefault(); event.stopPropagation(); setOver(null); if (draggingMaster) onDrop(target); } }); const cell = (start: string, days: number, className: string, plannedDays = 0, allocation?: { days: number; offset: number }) => { const valid = Boolean(getDropPlanningStart({ obra, zoom, targetDateOrPeriod: start })); const allocationStyle = allocation?.days ? { left: `${allocation.offset / days * 100}%`, width: `${allocation.days / days * 100}%` } : undefined; const allocationLabel = allocation?.days && allocation.days < days ? allocation.days : plannedDays || ''; return <div key={start} className={`${className} ${valid ? 'is-planned' : 'is-invalid-drop'} ${over === start ? 'is-drop-target' : ''}`} {...(valid ? events(start) : {})}><div className="co-cell-lanes"><TemporalLayer obra={obra} start={start} days={days} /><span className="co-cell-space">{(allocation?.days || plannedDays) ? <span className="co-allocation co-work-allocation" style={allocationStyle}>{allocationLabel}</span> : null}</span><MasterStrips obra={obra} bucketStart={start} bucketDays={days} /></div></div>; };
  if (zoom === 'day') return <div className="co-day-cells">{yearDays(2026).map((date) => cell(date, 1, 'co-day-cell'))}</div>;
  if (zoom === 'month') return <div className="co-month-cells">{monthlyHeader(2026).map((month) => { const days = monthDays(month.start); const valid = Boolean(getDropPlanningStart({ obra, zoom, targetDateOrPeriod: month.start })); return <div key={month.start} className={`co-month-cell co-month-cell--summary ${valid ? 'is-planned' : 'is-invalid-drop'} ${over === month.start ? 'is-drop-target' : ''}`} {...(valid ? events(month.start) : {})}><MonthSummary obra={obra} start={month.start} days={days} /></div>; })}</div>;
  return <div className="co-week-cells">{weeklyHeader(2026).map((week) => { const valid = Boolean(getDropPlanningStart({ obra, zoom, targetDateOrPeriod: week })); return <div key={week} className={`co-week-cell ${valid ? 'is-planned' : 'is-invalid-drop'} ${over === week ? 'is-drop-target' : ''}`} {...(valid ? events(week) : {})}><WeeklyLanes obra={obra} week={week} /></div>; })}</div>;
}
function MasterCells({ workload, zoom }: { workload: MestreWorkload; zoom: ZoomCronograma }) { const cells = zoom === 'day' ? workload.daily.map((item) => ({ days: item.obras.length, conflict: item.conflict })) : zoom === 'week' ? workload.weekly : monthlyHeader(2026).map((month) => { const items = workload.daily.filter((item) => item.date.slice(0, 7) === month.start.slice(0, 7)); return { days: items.filter((item) => item.obras.length).length, conflict: items.some((item) => item.conflict) }; }); return <div className={zoom === 'day' ? 'co-day-cells' : zoom === 'month' ? 'co-month-cells' : 'co-week-cells'}>{cells.map((cell, index) => <div className={`${zoom === 'day' ? 'co-day-cell' : zoom === 'month' ? 'co-month-cell' : 'co-week-cell'} co-resource-cell ${cell.conflict ? 'is-conflict' : ''}`} key={index}>{cell.days > 0 && <span className="co-resource-block" style={colorStyle(normalizeMestreKey(workload.mestre))} />}{cell.conflict && <WarningAmberRounded className="co-conflict-icon" />}</div>)}</div>; }
export const GanttGrid = memo(function GanttGrid({ view, zoom, obras, workloads, selectedId, draggingMaster, onSelect, onDropMaster }: Props) { const rows = view === 'obras' ? obras.length : workloads.length; const left = view === 'obras' ? <><span>Obra</span><span>Mestre inicial</span><span>Status</span><span>Emp.</span><span>Início</span><span>Dias</span></> : <><span>Mestre</span><span>Obras</span><span>Dias</span><span>Livres</span><span>Conflitos</span></>; return <section className={`co-gantt co-gantt--${view} ${draggingMaster ? 'is-dragging-master' : ''}`} aria-label="Cronograma anual"><div className="co-gantt-scroll"><div className={`co-gantt-grid co-gantt-grid--${zoom}`} style={{ '--row-count': rows } as React.CSSProperties}><div className="co-left-header">{left}</div><TimelineHeader zoom={zoom} />{view === 'obras' ? obras.map((obra) => <button type="button" className={`co-grid-row ${selectedId === obra.id ? 'is-selected' : ''}`} key={obra.id} onClick={() => onSelect(obra)}><div className="co-left-row"><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}</span><span>{obra.mestreInicial ?? <em>Sem mestre</em>}</span><span><StatusBadge status={obra.status} /></span><span>{obra.empresa}</span><span>{obra.inicioPlanejado}</span><span>{obra.tempoPlanejado}</span></div><ObraCells obra={obra} zoom={zoom} draggingMaster={draggingMaster} onDrop={(target) => onDropMaster(obra, draggingMaster!, target)} /></button>) : workloads.map((workload) => <div className="co-grid-row co-grid-row--resource" key={workload.mestre}><div className="co-left-row"><span className="co-master-name"><i className="co-master-swatch" style={colorStyle(normalizeMestreKey(workload.mestre))} />{workload.mestre}</span><span>{workload.obras.length}</span><span>{workload.diasProgramados}</span><span>{workload.freeDays} dias</span><span className={workload.conflictDays ? 'co-invalid-value' : ''}>{workload.conflictDays}</span></div><MasterCells workload={workload} zoom={zoom} /></div>)}</div></div>{!rows && <div className="co-empty">Nenhum resultado para os filtros selecionados.</div>}</section>; });
