import { Alert, Autocomplete, Button, FormControl, FormControlLabel, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useAuthorizationProfile } from '../hooks/useAuthorizationProfile';
import { listObrasAtivasParaSelecao, type ObraSelecaoOption } from '../services/obras.service';
import { listVeiculosAtivos, type VeiculoOption } from '../services/veiculos.service';
import { listMotoristasAtivosDetalhados, type MotoristaOption } from '../services/motoristas.service';
import { listMotivosCombustivelAtivos } from '../services/motivos.service';
import { saveCombustivelAndUpdateDieselPatio } from '../services/combustivelFirestore';

function int(value: string): number { return Number(value.replace(',', '.')); }
function snapshot(uid: string, nome: string) { return { uid: uid.trim(), nomeSnapshot: nome.trim() }; }

export default function CombustivelNovoPage() {
  const navigate = useNavigate(); const { currentUser, loading: authLoading } = useAuth();
  const { profile, loading: profileLoading } = useAuthorizationProfile(currentUser, authLoading);
  const [vehicles, setVehicles] = useState<VeiculoOption[]>([]); const [obras, setObras] = useState<ObraSelecaoOption[]>([]); const [people, setPeople] = useState<MotoristaOption[]>([]); const [motivos, setMotivos] = useState<string[]>([]);
  const [vehicle, setVehicle] = useState<VeiculoOption | null>(null); const [obra, setObra] = useState<ObraSelecaoOption | null>(null); const [receiver, setReceiver] = useState<MotoristaOption | null>(null); const [operator, setOperator] = useState<MotoristaOption | null>(null);
  const [mode, setMode] = useState<'direto' | 'galao'>('direto'); const [date, setDate] = useState(new Date().toISOString().slice(0, 16)); const [qa, setQa] = useState(''); const [lf, setLf] = useState(''); const [km, setKm] = useState(''); const [horimetro, setHorimetro] = useState(''); const [motivo, setMotivo] = useState(''); const [observacao, setObservacao] = useState(''); const [arla, setArla] = useState('0'); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([listVeiculosAtivos(), listObrasAtivasParaSelecao(), listMotoristasAtivosDetalhados(), listMotivosCombustivelAtivos()]).then(([v, o, p, m]) => { setVehicles(v); setObras(o); setPeople(p); setMotivos(m); }).catch((e) => setError(e instanceof Error ? e.message : 'Falha ao carregar opções.')); }, []);
  if (authLoading || profileLoading || !profile) return <Typography sx={{ p: 3 }}>Validando perfil de acesso...</Typography>;
  const authName = profile.nome || currentUser?.displayName || currentUser?.email || '';
  const selectedPerson = operator ?? (currentUser?.uid ? { id: currentUser.uid, nome: authName } : null);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError('');
    if (!currentUser?.uid || !selectedPerson || !receiver || !vehicle || !obra) return setError('Selecione item de frota, obra e para quem.');
    const quantity = int(qa); const finalAmount = int(lf); const reading = vehicle.categoria.toUpperCase() === 'PLACA' ? int(km) : int(horimetro);
    if (!Number.isInteger(quantity) || quantity <= 0 || !Number.isInteger(finalAmount)) return setError('Quantidade e montante final devem ser inteiros na unidade do contrato.');
    if (mode === 'direto' && !Number.isInteger(reading)) return setError('Informe uma leitura inteira válida.');
    const isVehicle = vehicle.categoria.toUpperCase() === 'PLACA';
    const itemFrota = isVehicle ? { uid: vehicle.id, tipo: 'veiculo' as const, identificadorSnapshot: vehicle.identificador, ...(mode === 'galao' && !km ? {} : { km: reading }) } : { uid: vehicle.id, tipo: 'maquina' as const, identificadorSnapshot: vehicle.identificador, ...(mode === 'galao' && !horimetro ? {} : { horimetro: reading }) };
    try { setSaving(true); await saveCombustivelAndUpdateDieselPatio({ data: new Date(date), quantidadeAbastecida: quantity, montanteAposMovimento: finalAmount, modalidadeAbastecimento: mode, frentista: snapshot(selectedPerson.id, selectedPerson.nome), paraQuem: snapshot(receiver.id, receiver.nome), autorLancamento: snapshot(currentUser.uid, authName), itemFrota, obra: { uid: obra.id, nomeSnapshot: obra.nome, ...(obra.local ? { localSnapshot: obra.local } : {}) }, motivo, arla: int(arla), observacao }); navigate('/combustivel'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar.'); } finally { setSaving(false); }
  };
  const isVehicle = vehicle?.categoria.toUpperCase() === 'PLACA';
  return <Stack component="form" onSubmit={submit} spacing={2} sx={{ p: 2, maxWidth: 1000 }}><Stack direction="row" justifyContent="space-between"><Typography variant="h5">Novo abastecimento V2</Typography><Button onClick={() => navigate('/combustivel')}>Voltar</Button></Stack>{error && <Alert severity="error">{error}</Alert>}<TextField label="Data" type="datetime-local" value={date} onChange={(e) => setDate(e.target.value)} InputLabelProps={{ shrink: true }} /><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><Autocomplete options={vehicles} value={vehicle} onChange={(_, v) => { setVehicle(v); setKm(''); setHorimetro(''); }} getOptionLabel={(v) => v.identificador} renderInput={(p) => <TextField {...p} label="Item da frota" required />} fullWidth /><Autocomplete options={obras} value={obra} onChange={(_, v) => setObra(v)} getOptionLabel={(v) => v.nome} renderInput={(p) => <TextField {...p} label="Obra" required />} fullWidth /></Stack><Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><Autocomplete options={people} value={receiver} onChange={(_, v) => setReceiver(v)} getOptionLabel={(v) => v.nome} renderInput={(p) => <TextField {...p} label="Para quem" required />} fullWidth /><Autocomplete options={people} value={operator} onChange={(_, v) => setOperator(v)} getOptionLabel={(v) => v.nome} renderInput={(p) => <TextField {...p} label="Frentista (opcional)" />} fullWidth /></Stack><FormControl fullWidth><InputLabel>Modalidade</InputLabel><Select value={mode} label="Modalidade" onChange={(e) => setMode(e.target.value as 'direto' | 'galao')}><MenuItem value="direto">Direto</MenuItem><MenuItem value="galao">Galão</MenuItem></Select></FormControl>{mode === 'direto' && (isVehicle ? <TextField label="KM" type="number" value={km} onChange={(e) => setKm(e.target.value)} inputProps={{ min: 0, step: 1 }} required /> : <TextField label="Horímetro" type="number" value={horimetro} onChange={(e) => setHorimetro(e.target.value)} inputProps={{ min: 0, step: 0.1 }} required />)}<Stack direction={{ xs: 'column', md: 'row' }} spacing={2}><TextField label="Quantidade (×10 L)" type="number" value={qa} onChange={(e) => setQa(e.target.value)} required fullWidth /><TextField label="Montante final (×10 L)" type="number" value={lf} onChange={(e) => setLf(e.target.value)} required fullWidth /><TextField label="ARLA (×10 L)" type="number" value={arla} onChange={(e) => setArla(e.target.value)} fullWidth /></Stack><Autocomplete freeSolo options={motivos} value={motivo} onInputChange={(_, v) => setMotivo(v)} renderInput={(p) => <TextField {...p} label="Motivo" required />} /><TextField label="Observação" value={observacao} onChange={(e) => setObservacao(e.target.value)} multiline minRows={2} /><Button type="submit" variant="contained" disabled={saving}>{saving ? 'Salvando...' : 'Salvar abastecimento'}</Button></Stack>;
}
