import { Alert, Box, Button, Chip, Divider, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { collection, getDocs } from 'firebase/firestore'; import { useEffect, useMemo, useState } from 'react'; import { db } from '../firebase';
import { prepareContractPreview, WRITES_ENABLED, type ObraV2, type RawStage } from '../features/monday-contratos/domain/conciliation';
export default function MondayContratosPage() {
  const [stages, setStages] = useState<RawStage[]>([]); const [obras, setObras] = useState<ObraV2[]>([]); const [selected, setSelected] = useState(0); const [loading, setLoading] = useState(true);
  useEffect(() => { void Promise.all([getDocs(collection(db, 'monday-gestao-obras-raw')), getDocs(collection(db, 'obras-v2'))]).then(([raw, works]) => { setStages(raw.docs.map((entry) => entry.data() as RawStage)); setObras(works.docs.map((entry) => ({ id: entry.id, ...entry.data() } as ObraV2))); }).finally(() => setLoading(false)); }, []);
  const stage = stages[selected]; const preview = useMemo(() => stage ? prepareContractPreview(stage.raw, null, obras, stage) : null, [stage, obras]);
  const setDecision = (subitemId: string, estado: 'PENDENTE' | 'IGNORADO' | 'VINCULADO_A_OBRA', obraId: string | null = null) => setStages((current) => current.map((entry, index) => index !== selected ? entry : { ...entry, conciliacao: { ...entry.conciliacao, subitems: { ...entry.conciliacao.subitems, [subitemId]: { estado, obraId } } } }));
  if (loading) return <Box p={3}>Carregando staging read-only…</Box>;
  return <Box p={3}><Stack spacing={2}><Typography variant="h5">Monday → contratos-v2 → obras-v2</Typography><Alert severity="warning">MODO READ-ONLY — Escrita em produção ainda não autorizada.</Alert>{!stage ? <Alert severity="info">Nenhum documento em monday-gestao-obras-raw. A tela não consulta nem grava no Monday; carregue o staging por fluxo autorizado futuro.</Alert> : <><TextField select label="Contrato no staging" value={selected} onChange={(event) => setSelected(Number(event.target.value))}>{stages.map((entry, index) => <MenuItem key={entry.sincronizacao.itemId} value={index}>{entry.raw.name}</MenuItem>)}</TextField><Paper sx={{ p: 2 }}><Typography variant="h6">{stage.raw.name}</Typography><Typography>Status: {preview!.contract.status ?? '—'}</Typography><Typography>Contrato: {preview!.contract.numeroContrato ?? '—'} · Ano: {preview!.contract.ano ?? '—'} · Empresa: {preview!.contract.empresa ?? '—'} · Início: {preview!.contract.inicio ?? '—'}</Typography><Divider sx={{ my: 2 }} /><Typography variant="h6">Conciliação</Typography>{Object.entries(stage.conciliacao.subitems).map(([subitemId, decision]) => <Stack key={subitemId} direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}><Chip label={`${stage.raw.subitems?.find((entry) => entry.id === subitemId)?.name ?? subitemId}: ${decision.estado}`} /><Typography variant="body2">Obra: {decision.obraId ?? 'não vinculada'}</Typography><Button size="small" onClick={() => setDecision(subitemId, 'PENDENTE')}>Pendente</Button><Button size="small" onClick={() => setDecision(subitemId, 'IGNORADO')}>Ignorar</Button></Stack>)}<Divider sx={{ my: 2 }} /><Typography variant="h6">Preview</Typography><Typography>CONTRATO: {preview!.contractOperation} contratos-v2/{stage.sincronizacao.itemId}</Typography><Typography>RAW: UPSERT monday-gestao-obras-raw/{stage.sincronizacao.itemId}</Typography>{preview!.obraPatches.map((entry) => <Typography key={entry.obraId}>OBRA: PATCH obras-v2/{entry.obraId} — {JSON.stringify(entry.patch)}</Typography>)}<Typography sx={{ mt: 1 }}>Pendentes: {preview!.pending}</Typography>{preview!.errors.map((error) => <Alert key={error} severity="error">{error}</Alert>)}<Button disabled={!WRITES_ENABLED || Boolean(preview!.errors.length)} variant="contained">Aplicar em produção</Button></Paper></>}</Stack></Box>;
}
