import KeyboardArrowDownRounded from '@mui/icons-material/KeyboardArrowDownRounded';
import MoreVertRounded from '@mui/icons-material/MoreVertRounded';
import WarningAmberRounded from '@mui/icons-material/WarningAmberRounded';
import { memo, useMemo, useState } from 'react';
import type { ContratoCronograma, ObraCronograma } from '../domain/models';
import { formatDateShort, todayCivil } from '../domain/temporal';
import { startedMasterPeriods } from '../domain/masterPlanningDetails';
import { getMestreColor, normalizeMestreKey } from '../domain/mestres';
import { MondaySubitemStatusControl } from './MondaySubitemStatusControl';
import type { MondaySubitemStatus } from '../../../services/mondaySubitemStatusService';
import { groupObrasByContract } from '../domain/contractGroups';
import { requiresContractReview } from '../data/source/rawCronogramaAdapter';

const colorStyle = (key: string): React.CSSProperties => ({ '--co-master-color': getMestreColor(key).background } as React.CSSProperties);
const missing = '—';
export function displayRawValue(value: unknown): string { if (value === null || value === undefined) return missing; if (typeof value === 'string') return value.trim() || missing; if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value); try { const serialized = JSON.stringify(value); return serialized && serialized !== '{}' ? serialized : missing; } catch { return String(value) || missing; } }

type Props = { obras: readonly ObraCronograma[]; contratos: ReadonlyMap<string, ContratoCronograma>; onOpenContract: (contrato: ContratoCronograma) => void; onSelect: (obra: ObraCronograma) => void; onSelectMasters: (obra: ObraCronograma) => void; onStatusConfirmed: (mondaySubitemId: string, status: MondaySubitemStatus) => void; sectionTitle: string; sectionCount: number; sectionExpanded: boolean; onToggleSection: () => void; variant?: 'finished' | 'not-started' };

export const ContractTextTable = memo(function ContractTextTable({ obras, contratos, onOpenContract, onSelect, onSelectMasters, onStatusConfirmed, sectionTitle, sectionCount, sectionExpanded, onToggleSection, variant = 'finished' }: Props) {
  const groups = useMemo(() => groupObrasByContract(obras), [obras]); const [expandedContracts, setExpandedContracts] = useState<Set<string>>(() => new Set()); const notStarted = variant === 'not-started';
  const toggle = (id: string) => setExpandedContracts((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const selectOnKey = (event: React.KeyboardEvent<HTMLDivElement>, obra: ObraCronograma) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onSelect(obra); } };
  return <section className={`co-text-table ${notStarted ? 'co-text-table--not-started' : ''}`} aria-label={sectionTitle}><div className="co-text-head"><button type="button" className="co-text-section-toggle" aria-expanded={sectionExpanded} aria-label={`${sectionExpanded ? 'Recolher' : 'Expandir'} ${sectionTitle}`} title={`${sectionExpanded ? 'Recolher' : 'Expandir'} ${sectionTitle}`} onClick={onToggleSection}><KeyboardArrowDownRounded className={sectionExpanded ? '' : 'is-collapsed'} />{sectionTitle} ({sectionCount})</button>{notStarted ? <><span>Contrato</span><span>Status</span><span>Emp.</span><span>Recurso</span><span>Ordem Ini</span><span>Ini</span><span>Fim</span></> : <><span>Mestres</span><span>Status</span></>}</div>{sectionExpanded && groups.map((group) => {
    const contrato = contratos.get(group.id); const expanded = expandedContracts.has(group.id); const needsReview = requiresContractReview(contrato); const obrasLabel = `${group.obras.length} ${group.obras.length === 1 ? 'obra' : 'obras'}`; const parent = contrato ?? group.obras[0]; const masters = [...new Map(group.obras.flatMap((obra) => obra.mestresPlanejados).map((mestre) => [mestre.nome, mestre])).values()]; const recurso = displayRawValue(contrato?.confirmacaoRecurso); const ordemInicio = displayRawValue(contrato?.ordemInicio); const inicio = formatDateShort(contrato?.inicio ?? null); const fim = formatDateShort(contrato?.fim ?? null);
    return <div className={`co-text-contract ${needsReview ? 'co-text-contract--review' : ''}`} key={group.id}><div className="co-text-row co-text-row--contract" role="button" tabIndex={0} aria-expanded={expanded} onClick={() => toggle(group.id)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); event.currentTarget.click(); } }}><span className="co-contract-name"><KeyboardArrowDownRounded className={expanded ? '' : 'is-collapsed'} /><button type="button" className="co-contract-details" aria-label={`Ver detalhes de ${group.name}`} onClick={(event) => { event.stopPropagation(); if (contrato) onOpenContract(contrato); }}><MoreVertRounded /></button>{group.name}{needsReview && <span className="co-contract-review-badge" title="Contrato sem LOTEs/subitems. Revisar no Monday." aria-label="Contrato sem LOTEs/subitems. Revisar no Monday."><WarningAmberRounded fontSize="inherit" />Analisar Contrato</span>}</span>{notStarted ? <><span>{displayRawValue(contrato?.numeroContrato)}</span><span>{obrasLabel}</span><span>{parent?.empresa || missing}</span><span>{recurso}</span><span>{ordemInicio}</span><span>{inicio}</span><span>{fim}</span></> : <><span className="co-masters-cell">{masters.length ? masters.map((mestre) => <i className="co-master-name-chip" key={mestre.nome} style={colorStyle(mestre.mestreKey ?? normalizeMestreKey(mestre.nome))}>{mestre.nome}</i>) : <em>Sem mestre</em>}</span><span className="co-contract-work-count">{obrasLabel}</span></>}</div>{expanded && group.obras.map((obra) => {
      const parentContract = contratos.get(obra.contratoId ?? group.id); const active = startedMasterPeriods(obra, todayCivil()); const review = obra.targetType === 'contrato'; const status = <MondaySubitemStatusControl obra={obra} canStart={notStarted} onStatusConfirmed={onStatusConfirmed} />;
      return notStarted ? <div role="button" tabIndex={0} className={`co-text-row co-text-row--child ${review ? 'co-text-row--review' : ''}`} key={obra.id} onClick={() => onSelect(obra)} onKeyDown={(event) => selectOnKey(event, obra)}><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}{review && <WarningAmberRounded className="co-review-icon" fontSize="inherit" titleAccess="Contrato sem LOTEs/subitems. Revisar no Monday." />}</span><span>{displayRawValue(parentContract?.numeroContrato)}</span><span>{status}</span><span>{obra.empresa || missing}</span><span>{displayRawValue(parentContract?.confirmacaoRecurso)}</span><span>{displayRawValue(parentContract?.ordemInicio)}</span><span>{formatDateShort(parentContract?.inicio ?? null)}</span><span>{formatDateShort(parentContract?.fim ?? null)}</span></div> : <div role="button" tabIndex={0} className="co-text-row co-text-row--child" key={obra.id} onClick={() => onSelect(obra)} onKeyDown={(event) => selectOnKey(event, obra)}><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}</span><span className="co-masters-cell" onClick={(event) => { event.stopPropagation(); onSelectMasters(obra); }}>{active.length ? active.map((mestre) => <i className="co-master-name-chip" key={mestre.key} style={colorStyle(mestre.key)}>{mestre.nome}</i>) : <em>Sem mestre</em>}</span><span>{status}</span></div>;
    })}</div>;
  })}{sectionExpanded && !groups.length && <div className="co-empty">Nenhum contrato nesta situação.</div>}</section>;
});
