import WarningAmberRounded from '@mui/icons-material/WarningAmberRounded';
import { type DragEvent, memo, useMemo, useState } from 'react';
import { TimelineHeader } from './TimelineHeader'; import { StatusBadge } from './StatusBadge';
import type { MestreWorkload, ObraCronograma, ZoomCronograma } from '../domain/models';
import { daysInMonth, monthDays, monthlyHeader, weeklyAllocation, weeklyHeader, yearDays } from '../domain/temporal';
import { getDropPlanningInterval } from '../domain/dropPlanning'; import { getMestreColor, normalizeMestreKey } from '../domain/mestres'; import { getObraTemporalSegments, getTemporalSegmentsInBucket } from '../domain/obraTemporal';
interface Props { view: 'obras' | 'mestres'; zoom: ZoomCronograma; obras: ObraCronograma[]; workloads: MestreWorkload[]; selectedId: string | null; draggingMaster: string | null; onSelect: (obra: ObraCronograma) => void; onDropMaster: (obra: ObraCronograma, nome: string, target: string) => void; }
const civilOffset = (start: string, date: string) => Math.round((Date.parse(`${date}T00:00:00Z`) - Date.parse(`${start}T00:00:00Z`)) / 86400000);
const colorStyle = (key: string): React.CSSProperties => ({ '--co-master-color': getMestreColor(key).background } as React.CSSProperties);
function TemporalLayer({ obra, start, days }: { obra: ObraCronograma; start: string; days: number }) { const segments = useMemo(() => getTemporalSegmentsInBucket(getObraTemporalSegments(obra), start, days), [obra, start, days]); return <span className="co-temporal-layer" aria-hidden="true">{segments.map((segment) => <i key={`${segment.type}-${segment.inicio}`} className={`co-temporal-segment is-${segment.type}`} style={{ left: `${civilOffset(start, segment.inicio) / days * 100}%`, width: `${(civilOffset(segment.inicio, segment.fim) + 1) / days * 100}%` }} />)}</span>; }
function MasterStrips({ obra, bucketStart, bucketDays }: { obra: ObraCronograma; bucketStart: string; bucketDays: number }) { return <span className="co-master-strips" aria-hidden="true">{obra.mestresPlanejados.map((mestre, index) => { const interval = getDropPlanningInterval({ obra: { ...obra, inicioPlanejado: mestre.inicio, tempoPlanejado: mestre.tempoPlanejado }, zoom: bucketDays === 1 ? 'day' : bucketDays === 7 ? 'week' : 'month', targetDateOrPeriod: bucketStart }); if (!interval) return null; return <i key={mestre.localId} className="co-master-strip" style={{ ...colorStyle(mestre.mestreKey ?? normalizeMestreKey(mestre.nome)), left: `${civilOffset(bucketStart, interval.inicio) / bucketDays * 100}%`, width: `${interval.tempoPlanejado / bucketDays * 100}%`, bottom: `${2 + (index % 3) * 4}px` }} />; })}</span>; }
function ObraCells({ obra, zoom, draggingMaster, onDrop }: { obra: ObraCronograma; zoom: ZoomCronograma; draggingMaster: string | null; onDrop: (target: string) => void }) { const [over, setOver] = useState<string | null>(null); const events = (target: string) => ({ onDragOver: (event: DragEvent) => { if (draggingMaster && getDropPlanningInterval({ obra, zoom, targetDateOrPeriod: target })) { event.preventDefault(); event.dataTransfer.dropEffect = 'copy'; } }, onDragEnter: () => { if (draggingMaster && getDropPlanningInterval({ obra, zoom, targetDateOrPeriod: target })) setOver(target); }, onDragLeave: () => setOver((current) => current === target ? null : current), onDrop: (event: DragEvent) => { event.preventDefault(); event.stopPropagation(); setOver(null); if (draggingMaster) onDrop(target); } });
  if (zoom === 'day') return <div className="co-day-cells">{yearDays(2026).map((date) => { const valid = Boolean(getDropPlanningInterval({ obra, zoom, targetDateOrPeriod: date })); return <div key={date} className={`co-day-cell ${valid ? 'is-planned' : ''} ${over === date ? 'is-drop-target' : ''}`} {...(valid ? events(date) : {})}><TemporalLayer obra={obra} start={date} days={1} />{valid && <MasterStrips obra={obra} bucketStart={date} bucketDays={1} />}</div>; })}</div>;
  if (zoom === 'month') return <div className="co-month-cells">{monthlyHeader(2026).map((month) => { const plannedDays = daysInMonth(obra.inicioPlanejado, obra.tempoPlanejado, month.start); return <div className={`co-month-cell ${over === month.start ? 'is-drop-target' : ''}`} key={month.start} {...(plannedDays ? events(month.start) : {})}><TemporalLayer obra={obra} start={month.start} days={monthDays(month.start)} />{plannedDays ? <><span className="co-allocation co-work-allocation">{plannedDays}</span><MasterStrips obra={obra} bucketStart={month.start} bucketDays={monthDays(month.start)} /></> : null}</div>; })}</div>;
  return <div className="co-week-cells">{weeklyHeader(2026).map((week) => { const allocation = weeklyAllocation(obra.inicioPlanejado, obra.tempoPlanejado, week); return <div className={`co-week-cell ${over === week ? 'is-drop-target' : ''}`} key={week} {...(allocation.days ? events(week) : {})}><TemporalLayer obra={obra} start={week} days={7} />{allocation.days ? <><span className="co-allocation co-work-allocation" style={{ left: `${allocation.offset / 7 * 100}%`, width: `${allocation.days / 7 * 100}%` }}>{allocation.days < 7 ? allocation.days : ''}</span><MasterStrips obra={obra} bucketStart={week} bucketDays={7} /></> : null}</div>; })}</div>; }
function MasterCells({ workload, zoom }: { workload: MestreWorkload; zoom: ZoomCronograma }) { const cells = zoom === 'day' ? workload.daily.map((item) => ({ days: item.obras.length, conflict: item.conflict })) : zoom === 'week' ? workload.weekly : monthlyHeader(2026).map((month) => { const items = workload.daily.filter((item) => item.date.slice(0, 7) === month.start.slice(0, 7)); return { days: items.filter((item) => item.obras.length).length, conflict: items.some((item) => item.conflict) }; }); return <div className={zoom === 'day' ? 'co-day-cells' : zoom === 'month' ? 'co-month-cells' : 'co-week-cells'}>{cells.map((cell, index) => <div className={`${zoom === 'day' ? 'co-day-cell' : zoom === 'month' ? 'co-month-cell' : 'co-week-cell'} co-resource-cell ${cell.conflict ? 'is-conflict' : ''}`} key={index}>{cell.days > 0 && <span className="co-resource-block" style={colorStyle(normalizeMestreKey(workload.mestre))} />}{cell.conflict && <WarningAmberRounded className="co-conflict-icon" />}</div>)}</div>; }
export const GanttGrid = memo(function GanttGrid({ view, zoom, obras, workloads, selectedId, draggingMaster, onSelect, onDropMaster }: Props) { const rows = view === 'obras' ? obras.length : workloads.length; return <section className={`co-gantt co-gantt--${view} ${draggingMaster ? 'is-dragging-master' : ''}`} aria-label="Cronograma anual"><div className="co-gantt-scroll"><div className={`co-gantt-grid co-gantt-grid--${zoom}`} style={{ '--row-count': rows } as React.CSSProperties}><div className="co-left-header">{view === 'obras' ? <><span>Obra</span><span>Mestre inicial</span><span>Status</span><span>Emp.</span><span>Início</span><span>Dias</span></> : <><span>Mestre</span><span>Obras</span><span>Dias</span><span>Livres</span><span>Conflitos</span></>}</div><TimelineHeader zoom={zoom} />{view === 'obras' ? obras.map((obra) => <button type="button" className={`co-grid-row ${selectedId === obra.id ? 'is-selected' : ''}`} key={obra.id} onClick={() => onSelect(obra)}><div className="co-left-row"><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}</span><span>{obra.mestreInicial ?? <em>Sem mestre</em>}</span><span><StatusBadge status={obra.status} /></span><span>{obra.empresa}</span><span>{obra.inicioPlanejado}</span><span>{obra.tempoPlanejado}</span></div><ObraCells obra={obra} zoom={zoom} draggingMaster={draggingMaster} onDrop={(target) => onDropMaster(obra, draggingMaster!, target)} /></button>) : workloads.map((workload) => <div className="co-grid-row co-grid-row--resource" key={workload.mestre}><div className="co-left-row"><span className="co-master-name"><i className="co-master-swatch" style={colorStyle(normalizeMestreKey(workload.mestre))} />{workload.mestre}</span><span>{workload.obras.length}</span><span>{workload.diasProgramados}</span><span>{workload.freeDays} dias</span><span className={workload.conflictDays ? 'co-invalid-value' : ''}>{workload.conflictDays}</span></div><MasterCells workload={workload} zoom={zoom} /></div>)}</div></div>{!rows && <div className="co-empty">Nenhum resultado para os filtros selecionados.</div>}</section>; });
