import { MONTHS, type ZoomCronograma } from '../domain/models';
import { dailyHeader, monthlyHeader, todayCivil, weeklyMonthGroups, weeklyTimelineCells } from '../domain/temporal';
export function yearSegments(dates: readonly string[]) { return dates.reduce<Array<{ year: number; count: number }>>((segments, date) => { const year = Number(date.slice(0, 4)); const last = segments.at(-1); if (last?.year === year) last.count++; else segments.push({ year, count: 1 }); return segments; }, []); }
const YearLine = ({ dates, unit }: { dates: readonly string[]; unit: string }) => <div className="co-timeline-year" style={{ gridTemplateColumns: `repeat(${dates.length}, ${unit})` }}>{yearSegments(dates).map((segment) => <div key={segment.year} style={{ gridColumn: `span ${segment.count}` }}>{segment.year}</div>)}</div>;
export function TimelineHeader({ zoom, year = 2026, years = [year] }: { zoom: ZoomCronograma; year?: number; years?: number[] }) {
  if (zoom === 'year') { const currentYear = Number(todayCivil().slice(0, 4)); return <div className="co-timeline-header"><div className="co-years">{years.map((item) => <div key={item} className={item === currentYear ? 'is-current-year' : ''}>{item}</div>)}</div></div>; }
  if (zoom === 'month') return <div className="co-timeline-header"><YearLine dates={monthlyHeader(year).map((month) => month.start)} unit="var(--co-month-width)" /><div className="co-months co-months--single">{monthlyHeader(year).map((month) => <div key={month.start}>{month.label}</div>)}</div></div>;
  if (zoom === 'week') { const weeks = weeklyTimelineCells(year); return <div className="co-timeline-header"><YearLine dates={weeks.map((week) => week.date)} unit="var(--co-week-width)" /><div className="co-months co-months--weeks" style={{ gridTemplateColumns: `repeat(${weeks.length}, var(--co-week-width))` }}>{weeklyMonthGroups(year).map((month) => <div key={month.start} style={{ gridColumn: `span ${month.weeks}` }}>{month.label}</div>)}</div><div className="co-weeks" style={{ gridTemplateColumns: `repeat(${weeks.length}, var(--co-week-width))` }}>{weeks.map((week, index) => <div key={week.date}>S{index + 1}</div>)}</div></div>; }
  const days = dailyHeader(year); return <div className="co-timeline-header co-timeline-header--days"><YearLine dates={days.map((day) => day.date)} unit="var(--co-day-width)" /><div className="co-months co-months--days">{MONTHS.map((month, index) => <div key={month} style={{ gridColumn: `span ${days.filter((day) => Number(day.date.slice(5, 7)) === index + 1).length}` }}>{month}</div>)}</div><div className="co-days">{days.map((day) => <div key={day.date} className={`${day.isWeekStart ? 'is-week-start ' : ''}${day.date === todayCivil() ? 'is-today' : ''}`}>{day.label}</div>)}</div></div>;
}
