import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { normalizarPlacaParaErp } from './normalizacao.mjs';
import { consultarQueryErp, DEFAULT_ERP360_API_BASE_URL, ErpClientError } from './erp-client.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(root, 'output');
const request = Object.freeze({ DataInicial: '2025-01-01', DataFinal: '2026-09-25', Placa: normalizarPlacaParaErp('JBJ-4J22') });
const baseline = Object.freeze({ firebase: 104167.30, erp: { 2025: 25882.33, 2026: 18594.16, total: 44476.49 }, lancamentos: { 2025: 45, 2026: 48, total: 93 } });
const normalizeKey = (value) => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');
function get(row, ...names) { const map = new Map(Object.keys(row ?? {}).map((name) => [normalizeKey(name), name])); for (const name of names) { const actual = map.get(normalizeKey(name)); if (actual !== undefined) return row[actual]; } return null; }
function num(value) { if (typeof value === 'number') return Number.isFinite(value) ? value : 0; const text = String(value ?? '').trim(); const parsed = Number(text.includes(',') ? text.replace(/\./g, '').replace(',', '.') : text); return Number.isFinite(parsed) ? parsed : 0; }
function year(row) { const value = get(row, 'ano', 'exercicio', 'data', 'data_lancamento', 'dataemissao', 'mes'); const match = String(value ?? '').match(/20\d{2}/); return match ? Number(match[0]) : null; }
function month(row) { const value = String(get(row, 'mes', 'data', 'data_lancamento', 'dataemissao') ?? ''); const iso = value.match(/(20\d{2})[-/](\d{1,2})/); if (iso) return `${iso[1]}-${iso[2].padStart(2, '0')}`; const br = value.match(/\d{1,2}[-/](\d{1,2})[-/](20\d{2})/); return br ? `${br[2]}-${br[1].padStart(2, '0')}` : (year(row) ? String(year(row)) : 'sem_mes'); }
const sum = (rows, name) => rows.reduce((total, row) => total + num(get(row, name)), 0);
function annual(rows, fields) { return Object.fromEntries([2025, 2026].map((currentYear) => { const selected = rows.filter((row) => year(row) === currentYear); return [currentYear, { linhas: selected.length, ...Object.fromEntries(fields.map((name) => [name, sum(selected, name)])) }]; })); }
function grouped(rows, fields, values) { const results = new Map(); for (const row of rows) { const item = Object.fromEntries(fields.map((name) => [name, name === 'mes' ? month(row) : get(row, name)])); const id = JSON.stringify(item); const entry = results.get(id) ?? { ...item, linhas: 0, ...Object.fromEntries(values.map((name) => [name, 0])) }; entry.linhas++; values.forEach((name) => { entry[name] += num(get(row, name)); }); results.set(id, entry); } return [...results.values()]; }
function distinct(rows, names) { return [...new Set(rows.map((row) => names.map((name) => get(row, name)).filter((v) => v != null && String(v).trim()).join(' | ')).filter(Boolean))].sort(); }
function audit46(rows) { const fields = ['qtd_lancamentos', 'receita', 'despesa', 'valor_resultado']; return { geral: { linhas: rows.length, ...Object.fromEntries(fields.map((name) => [name, sum(rows, name)])) }, anual: annual(rows, fields), agrupamentos: { mes: grouped(rows, ['mes'], fields), conta: grouped(rows, ['conta', 'conta_descricao'], fields), empresa: grouped(rows, ['empresa'], fields), subcentro: grouped(rows, ['cod_subcentro', 'subcentro'], fields) } }; }
function movementValue(row, kind) { const marker = [get(row, 'natureza'), get(row, 'tipo_movimento')].map((v) => String(v ?? '').trim().toUpperCase()).join(' '); const rateio = num(get(row, 'valor_rateio')); if (kind === 'despesa') return /DESP|^D\b|DEBIT/.test(marker) ? rateio : 0; if (kind === 'receita') return /RECE|^R\b|CREDIT/.test(marker) ? rateio : 0; return 0; }
function sum47(rows, kind) { return rows.reduce((total, row) => total + (kind === 'valor_rateio' || kind === 'valor_resultado' ? num(get(row, kind)) : movementValue(row, kind)), 0); }
function audit47(rows) { const fields = ['receita', 'despesa', 'valor_rateio', 'valor_resultado']; const annual47 = Object.fromEntries([2025, 2026].map((y) => { const selected = rows.filter((row) => year(row) === y); return [y, { linhas: selected.length, notas: new Set(selected.map((row) => String(get(row, 'numero_nota', 'cod_nota') ?? '')).filter(Boolean)).size, ...Object.fromEntries(fields.map((name) => [name, sum47(selected, name)])) }]; })); const plate = rows.reduce((counts, row) => { const value = get(row, 'placa_nota'); if (value == null || !String(value).trim()) counts.vazia++; else if (normalizarPlacaParaErp(value) === request.Placa) counts.compativel++; else counts.divergente++; return counts; }, { compativel: 0, vazia: 0, divergente: 0 }); const transfer = rows.filter((row) => String(get(row, 'transferencia') ?? '').trim().toUpperCase() === 'S'); const project = (selected) => ({ ...Object.fromEntries(fields.map((name) => [name, sum47(selected, name)])) }); const classified = rows.map((row) => ({ ...row, receita: movementValue(row, 'receita'), despesa: movementValue(row, 'despesa') })); return { geral: { linhas: rows.length, notas_distintas: new Set(rows.map((row) => String(get(row, 'numero_nota', 'cod_nota') ?? '')).filter(Boolean)).size, fornecedores_distintos: new Set(rows.map((row) => String(get(row, 'cliente_fornecedor', 'fornecedor') ?? '')).filter(Boolean)).size, ...project(rows) }, anual: annual47, identificacaoPlaca: plate, classificacaoMovimento: { natureza: distinct(rows, ['natureza']), tipo_movimento: distinct(rows, ['tipo_movimento']) }, transferencias: { quantidade: transfer.length, ...project(transfer) }, agrupamentos: { mes: grouped(classified, ['mes'], fields), conta: grouped(classified, ['conta', 'conta_descricao'], fields), fornecedor: grouped(classified, ['cliente_fornecedor'], fields), empresa: grouped(classified, ['empresa'], fields), subcentro: grouped(classified, ['cod_subcentro', 'subcentro'], fields) } }; }
function compare(data) { const result = {}; [2025, 2026].forEach((y) => { const consulta = data[y].despesa; const diferenca = consulta - baseline.erp[y]; result[y] = { consulta, baseline: baseline.erp[y], diferenca, diferencaPercentual: diferenca / baseline.erp[y] * 100 }; }); const consulta = result[2025].consulta + result[2026].consulta; const diferenca = consulta - baseline.erp.total; result.total = { consulta, baseline: baseline.erp.total, diferenca, diferencaPercentual: diferenca / baseline.erp.total * 100 }; return result; }
const brl = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
function md(report) { const a = report.auditoria.query46; const b = report.auditoria.query47; const c = report.comparacaoBaseline; const comp = (label, value) => `| ${label} | ${brl(value.consulta)} | ${brl(value.baseline)} | ${brl(value.diferenca)} | ${value.diferencaPercentual.toFixed(2).replace('.', ',')}% |`; return `# Auditoria ERP — JBJ4J22\n\n**SUCESSO** — execução exclusivamente read-only.\n\n## Consultas\n\n| Query | HTTP | Content-Type | Linhas | Campos do primeiro registro |\n| --- | ---: | --- | ---: | --- |\n| 46 | ${report.erp.query46.httpStatus} | ${report.erp.query46.contentType} | ${report.erp.query46.rowCount} | ${report.erp.query46.firstRecordFields.join(', ')} |\n| 47 | ${report.erp.query47.httpStatus} | ${report.erp.query47.contentType} | ${report.erp.query47.rowCount} | ${report.erp.query47.firstRecordFields.join(', ')} |\n\n## Q46 × Q47\n\n| Métrica | Q46 | Q47 |\n| --- | ---: | ---: |\n| Despesas | ${brl(a.geral.despesa)} | ${brl(b.geral.despesa)} |\n| Receitas | ${brl(a.geral.receita)} | ${brl(b.geral.receita)} |\n| Resultado | ${brl(a.geral.valor_resultado)} | ${brl(b.geral.valor_resultado)} |\n| Lançamentos / notas | ${a.geral.qtd_lancamentos} | ${b.geral.notas_distintas} |\n\n## Comparação com baseline (despesa)\n\n| Consulta/período | Consulta | Baseline | Diferença | % |\n| --- | ---: | ---: | ---: | ---: |\n${comp('Q46 2025', c.query46[2025])}\n${comp('Q46 2026', c.query46[2026])}\n${comp('Q46 Total', c.query46.total)}\n${comp('Q47 2025', c.query47[2025])}\n${comp('Q47 2026', c.query47[2026])}\n${comp('Q47 Total', c.query47.total)}\n\nDetalhamento anual, mensal, por conta, fornecedor, empresa e subcentro: resultado-jbj.json.\n\n- Token presente no ambiente: SIM; credencial exposta: NÃO; segredo persistido no projeto: NÃO.\n- .env rastreado: NÃO; .gitignore protege .env: NÃO.\n- Total 4 é **EXPERIMENTAL — POSSÍVEL DUPLA CONTAGEM ERP**.\n`; }
async function main() { if (typeof process.env.ERP360_API_TOKEN !== 'string' || !process.env.ERP360_API_TOKEN.trim()) { console.log('ERP_API_TOKEN_MISSING'); process.exitCode = 2; return; } const q46 = await consultarQueryErp({ queryId: 46, parameters: request }); console.log(JSON.stringify({ query: 46, ...q46.metadata })); const q47 = await consultarQueryErp({ queryId: 47, parameters: request }); console.log(JSON.stringify({ query: 47, ...q47.metadata })); const query46 = audit46(q46.rows); const query47 = audit47(q47.rows); const report = { status: 'SUCESSO', request, metadata: { modo: 'READ-ONLY', credenciaisExpostas: false, firebaseConsultado: false, firebaseEscrito: false, deployExecutado: false, aplicacaoWebAlterada: false, firebaseRulesAlteradas: false }, erp: { baseUrl: process.env.ERP360_API_BASE_URL || DEFAULT_ERP360_API_BASE_URL, autenticacaoFuncional: true, query46: q46.metadata, query47: q47.metadata }, auditoria: { query46, query47 }, identificacao: { query46: { cod_subcentro: distinct(q46.rows, ['cod_subcentro']), subcentro: distinct(q46.rows, ['subcentro']) }, query47: { cod_subcentro: distinct(q47.rows, ['cod_subcentro']), subcentro: distinct(q47.rows, ['subcentro']), placa_nota: distinct(q47.rows, ['placa_nota']) } }, baseline, comparacaoBaseline: { query46: compare(query46.anual), query47: compare(query47.anual) }, totais: { firebase: baseline.firebase, firebaseMaisQ46: baseline.firebase + query46.geral.despesa, firebaseMaisQ47: baseline.firebase + query47.geral.despesa, firebaseMaisQ46MaisQ47: baseline.firebase + query46.geral.despesa + query47.geral.despesa, avisoTotal4: 'EXPERIMENTAL — POSSÍVEL DUPLA CONTAGEM ERP' }, q46VsQ47: { geral: { q46: query46.geral, q47: query47.geral }, anual: { q46: query46.anual, q47: query47.anual }, mensal: { q46: query46.agrupamentos.mes, q47: query47.agrupamentos.mes } }, seguranca: { envRastreado: false, envProtegido: false, segredoPersistidoNoProjeto: false } }; await mkdir(output, { recursive: true }); await writeFile(resolve(output, 'resultado-jbj.json'), `${JSON.stringify(report, null, 2)}\n`, 'utf8'); await writeFile(resolve(output, 'resultado-jbj.md'), md(report), 'utf8'); console.log(JSON.stringify({ status: report.status, output: ['output/resultado-jbj.json', 'output/resultado-jbj.md'] })); }
main().catch((error) => { const code = error instanceof ErpClientError ? error.code : 'ERP_UNEXPECTED_ERROR'; console.log(code); if (error instanceof ErpClientError && error.metadata?.httpStatus) console.log(JSON.stringify({ httpStatus: error.metadata.httpStatus })); process.exitCode = 1; });
