import WarningAmberRounded from '@mui/icons-material/WarningAmberRounded';
import { memo } from 'react';
import { TimelineHeader } from './TimelineHeader';
import { StatusBadge } from './StatusBadge';
import type { MestreWorkload, ObraCronograma, ZoomCronograma } from '../domain/models';
import { daysInMonth, daysInWeek, monthlyHeader, weeklyHeader, yearDays } from '../domain/temporal';
interface Props { view: 'obras' | 'mestres'; zoom: ZoomCronograma; obras: ObraCronograma[]; workloads: MestreWorkload[]; selectedId: string | null; onSelect: (obra: ObraCronograma) => void; }
function colorIndex(name: string | null): number { return [...(name ?? '')].reduce((value, char) => value + char.charCodeAt(0), 0) % 8; }
function ObraCells({ obra, zoom }: { obra: ObraCronograma; zoom: ZoomCronograma }) { const cells = zoom === 'day' ? yearDays(2026).map((date) => ({ key: date, days: obra.inicioPlanejado <= date && date <= new Date(`${obra.inicioPlanejado}T00:00:00Z`).toISOString().slice(0, 10).replace(/.*/, '') ? 0 : 0 })) : []; if (zoom === 'day') return <div className="co-day-cells">{yearDays(2026).map((date) => { const active = date >= obra.inicioPlanejado && date <= new Date(new Date(`${obra.inicioPlanejado}T00:00:00Z`).getTime() + (obra.tempoPlanejado - 1) * 86400000).toISOString().slice(0, 10); return <div key={date} className={`co-day-cell ${active ? `is-active co-color-${colorIndex(obra.mestreInicial)}` : ''}`} />; })}</div>; if (zoom === 'month') return <div className="co-month-cells">{monthlyHeader(2026).map((month) => { const days = daysInMonth(obra.inicioPlanejado, obra.tempoPlanejado, month.start); return <div className="co-month-cell" key={month.start}>{days ? <span className={`co-allocation co-color-${colorIndex(obra.mestreInicial)}`}>{days}</span> : null}</div>; })}</div>; return <div className="co-week-cells">{weeklyHeader(2026).map((week) => { const days = daysInWeek(obra.inicioPlanejado, obra.tempoPlanejado, week); return <div className="co-week-cell" key={week}>{days ? <span className={`co-allocation co-color-${colorIndex(obra.mestreInicial)}`} style={{ width: `${Math.max(18, days / 7 * 100)}%` }}>{days < 7 ? days : ''}</span> : null}</div>; })}</div>; }
function MasterCells({ workload, zoom }: { workload: MestreWorkload; zoom: ZoomCronograma }) { const dates = zoom === 'day' ? yearDays(2026) : zoom === 'week' ? weeklyHeader(2026) : monthlyHeader(2026).map((month) => month.start); return <div className={zoom === 'day' ? 'co-day-cells' : zoom === 'month' ? 'co-month-cells' : 'co-week-cells'}>{dates.map((date) => { const daily = zoom === 'day' ? workload.daily.filter((item) => item.date === date) : zoom === 'week' ? workload.daily.filter((item) => item.date >= date && item.date < new Date(new Date(`${date}T00:00:00Z`).getTime() + 7 * 86400000).toISOString().slice(0, 10)) : workload.daily.filter((item) => item.date.slice(0, 7) === date.slice(0, 7)); const active = daily.some((item) => item.obras.length); const conflict = daily.some((item) => item.conflict); return <div className={`${zoom === 'day' ? 'co-day-cell' : zoom === 'month' ? 'co-month-cell' : 'co-week-cell'} co-resource-cell ${conflict ? 'is-conflict' : ''}`} key={date}>{active && <span className="co-resource-block co-color-1" />}{conflict && <WarningAmberRounded className="co-conflict-icon" />}</div>; })}</div>; }
export const GanttGrid = memo(function GanttGrid({ view, zoom, obras, workloads, selectedId, onSelect }: Props) { const rows = view === 'obras' ? obras.length : workloads.length; return <section className={`co-gantt co-gantt--${view}`} aria-label="Cronograma anual"><div className="co-gantt-scroll"><div className={`co-gantt-grid co-gantt-grid--${zoom}`} style={{ '--row-count': rows } as React.CSSProperties}><div className="co-left-header">{view === 'obras' ? <><span>Obra</span><span>Mestre inicial</span><span>Status</span><span>Emp.</span><span>Início</span><span>Dias</span></> : <><span>Mestre</span><span>Obras</span><span>Dias</span><span>Livres</span><span>Conflitos</span></>}</div><TimelineHeader zoom={zoom} />{view === 'obras' ? obras.map((obra) => <button type="button" className={`co-grid-row ${selectedId === obra.id ? 'is-selected' : ''}`} key={obra.id} onClick={() => onSelect(obra)}><div className="co-left-row"><span className="co-work-name" title={obra.nomeObra}>{obra.nomeObra}</span><span>{obra.mestreInicial ?? <em>Sem mestre</em>}</span><span><StatusBadge status={obra.status} /></span><span>{obra.empresa}</span><span>{obra.inicioPlanejado}</span><span>{obra.tempoPlanejado}</span></div><ObraCells obra={obra} zoom={zoom} /></button>) : workloads.map((workload) => <div className="co-grid-row co-grid-row--resource" key={workload.mestre}><div className="co-left-row"><span className="co-master-name"><i className={`co-master-swatch co-color-${colorIndex(workload.mestre)}`} />{workload.mestre}</span><span>{workload.obras.length}</span><span>{workload.diasProgramados}</span><span>{workload.freeDays} dias</span><span className={workload.conflictDays ? 'co-invalid-value' : ''}>{workload.conflictDays}</span></div><MasterCells workload={workload} zoom={zoom} /></div>)}</div></div>{!rows && <div className="co-empty">Nenhum resultado para os filtros selecionados.</div>}</section>; });
