export interface Registro {
  id: string;
  data?: any;
  lf?: number;
  qa?: number;
  li?: number;
  arla?: number;
  diesel?: number;
  motorista?: string;
  para_quem?: string;
  placa?: string;
  extra?: string | null;
  local?: string;
  motivo?: string;
  observacao?: string;
  obra?: string;
  km?: number | string | null;
  semKm?: string;
  tipoPlaca?: boolean;
  schema?: 'entrada-v2' | 'saida-v2' | 'legado';
  isFuelOutput?: boolean;
  schemaVersion?: number;
  quantidadeAbastecida?: number;
  valorAbastecimento?: number;
  montanteAntes?: number;
  montanteAposMovimento?: number;
  estoqueAntes?: number;
  estoqueAposMovimento?: number;
  modalidadeAbastecimento?: 'direto' | 'galao';
  itemFrotaUid?: string;
  itemFrotaTipo?: 'veiculo' | 'maquina' | null;
  identificadorSnapshot?: string;
  horimetro?: number;
  frentista?: string;
  paraQuem?: string;
  autorLancamento?: string;
  obraUid?: string;
}
